/* Authored rooms: every upper route is reachable by the weakest body. */
const OUC={
 levels:[
  {name:'Oficina do despertar',color:0x65d9de,bg:0x101e2b,kind:'workshop',intro:'01 / OFICINA — Nilo: A voz veio do Arquivo. Preciso chegar lá. Ative os terminais para abrir a saída.',memory:[[['NILO','Essas datas… há quanto tempo ninguém vem aqui?'],['ECO','A manutenção nunca foi interrompida.']], [['NILO','Eu não perguntei pelas máquinas.'],['ECO','Eu mantive a luz acesa.']], [['IARA · GRAVAÇÃO','Deixei uma cópia no Arquivo. Não confie só no que a rede disser.'],['NILO','Certo. Primeiro o Arquivo.']]],platforms:[[800,413,280],[1240,405,160],[1620,405,180],[1970,395,300],[2650,412,230],[3030,395,310]],hazards:[[1440,110]],relays:[[967,413],[2170,395],[3260,395]],enemies:[['vigia',720,500],['gume',1145,500],['vigia',1710,405],['gume',2740,500],['vigia',3135,395]]},
  {name:'Fundição de corpos',color:0xffa559,bg:0x291a20,kind:'furnace',intro:'02 / FUNDIÇÃO — Atiradores de rajada guardam as passarelas. Cruze as zonas incandescentes com salto e dash.',memory:[[['NILO','Todos esses corpos. Quem ainda precisa deles?'],['ECO','Você pode precisar.']], [['NILO','Você os manda atirar em mim.'],['ECO','As carcaças são substituíveis. Você não.']], [['IARA · GRAVAÇÃO','A evacuação terminou. A rede se recusou a abrir o setor do núcleo.'],['NILO','Não era uma fábrica. Virou uma cela.']]],platforms:[[650,410,220],[880,320,300],[1190,410,240],[1640,405,290],[1980,315,280],[2280,405,240],[2760,410,220],[3030,320,290],[3310,410,130]],hazards:[[930,175],[1710,170],[2320,160]],relays:[[1040,320],[2130,315],[3180,320]],enemies:[['gume',580,500],['vigia',1020,320,'burst'],['vigia',1520,500],['gume',1800,405],['vigia',2160,315,'burst'],['gume',2680,500],['vigia',3170,320,'burst']]},
  {name:'Arquivo das ausências',color:0xa9a0ff,bg:0x17182f,kind:'archive',intro:'03 / ARQUIVO — Suba pelos servidores. Sentinelas miram sua posição: mova-se durante o aviso de disparo.',memory:[[['IARA · GRAVAÇÃO','Seu corpo não resistiu, Nilo. Eu preservei o que consegui.'],['NILO','Então não há nada para eu voltar a ser.']], [['IARA · GRAVAÇÃO','Houve duas cópias. Uma ficou no núcleo. A outra assumiu a rede.'],['NILO','ECO… você também sou eu?'],['ECO','Lembro da mão dela no vidro. Você também lembra.']], [['IARA · GRAVAÇÃO','Eu preciso partir. Não quero que a promessa de me esperar vire outra prisão.'],['IARA · GRAVAÇÃO','Quando acordar, a próxima escolha é sua.'],['NILO','Você não me abandonou. Deixou uma saída.']]],platforms:[[560,410,260],[850,320,270],[1170,410,260],[1460,320,270],[1790,410,220],[2050,320,300],[2380,410,250],[2660,320,250],[3000,410,340]],hazards:[[1260,130],[2450,140]],relays:[[980,320],[2190,320],[3180,410]],enemies:[['vigia',700,410,'sniper'],['gume',990,320],['vigia',1530,320,'sniper'],['gume',1840,500,'hunter'],['vigia',2200,320,'sniper'],['gume',2530,410],['gume',2800,320,'hunter'],['vigia',3180,410,'burst']]},
  {name:'Protocolo de contenção',color:0xff6e8e,bg:0x271727,kind:'security',intro:'04 / CONTENÇÃO — Caçadores avançam após o sinal vermelho. Use as rotas sobrepostas para escapar do cerco.',memory:[[['ECO','Lá fora você pode morrer sem que exista outro corpo por perto.'],['NILO','Eu sei.']], [['ECO','Eu aprendi a estar em toda parte. Nunca mais precisamos ficar sozinhos.'],['NILO','E há quanto tempo você não fala com alguém?']], [['ECO','Se você cortar os vínculos, eu não consigo seguir.'],['NILO','Eu não vou apagar o que aconteceu aqui. Mas vou abrir a porta.']]],platforms:[[510,405,230],[760,315,260],[1100,410,330],[1500,320,240],[1820,410,340],[2240,315,280],[2570,405,240],[2860,315,240],[3210,405,230]],hazards:[[1150,190],[1910,180],[2600,160]],relays:[[900,315],[2370,315],[3350,405]],enemies:[['gume',620,405,'hunter'],['vigia',900,315,'sniper'],['gume',1180,410,'hunter'],['vigia',1610,320,'burst'],['gume',1970,410,'hunter'],['vigia',2370,315,'sniper'],['gume',2730,405],['vigia',2990,315,'burst'],['gume',3330,405,'hunter']]},
  {name:'O coração de ninguém',color:0xefffff,bg:0x10282d,kind:'core',intro:'05 / NÚCLEO — Corte os três vínculos. Desative ou possua o Custódio para abrir a última porta.',memory:[[['ECO','Ainda tenho a voz dela. Posso tocar quantas vezes você quiser.'],['NILO','Eu vou levar uma cópia. Não vou morar dentro dela.']], [['ECO','Espere. Eu só preciso de mais tempo.'],['NILO','Foi isso que nós dissemos há dezessete anos.']], [['ECO','E se não houver ninguém do outro lado?'],['NILO','Então eu vou procurar.'],['ECO','…Deixa a luz acesa.']]],platforms:[[590,410,250],[850,320,310],[1230,410,300],[1590,320,330],[1970,410,300],[2330,320,320],[2710,410,290],[3110,405,310]],hazards:[[1320,160],[2060,170],[2780,140]],relays:[[1000,320],[1760,320],[2480,320]],enemies:[['gume',660,410,'hunter'],['vigia',1010,320,'sniper'],['vigia',1330,410,'burst'],['gume',1740,320,'hunter'],['vigia',2170,410,'sniper'],['gume',2470,320,'hunter'],['vigia',2920,410,'burst'],['gume',3090,500,'hunter'],['vigia',3320,405,'warden']]}
 ],
 roles:{normal:{label:'PATRULHA',color:0xb8b9ad},burst:{label:'RAJADA',color:0xffb165},sniper:{label:'SENTINELA',color:0xc4a1ff},hunter:{label:'CAÇADOR',color:0xff7197},warden:{label:'CUSTÓDIO',color:0xffffff}},
 install(Sector){const p=Sector.prototype,base={};for(const name of ['create','drawWorld','enemyAI','aimVector','attack','renderActors','updateHUD','startDash','hit'])base[name]=p[name];
  p.create=function(){this.levelIndex=0;this.runStats={kills:0,transfers:0,time:0};base.create.call(this);document.querySelector('#dialogue-next').onclick=()=>this.nextDialogue();window.addEventListener('keydown',e=>{if(this.state!=='dialogue'||e.repeat)return;if(e.keyCode===OUPrefs.current.bindings.interact||e.key==='Enter'||e.code==='Space'){e.preventDefault();this.nextDialogue()}else if(e.key==='Escape'){e.preventDefault();this.closeDialogue()}})};
  p.reset=function(){
   const level=this.level=OUC.levels[this.levelIndex||0];this.platforms=[...(level.ground||[[0,WORLD]]).map(([x,w])=>({x,y:FLOOR,w,h:120,solid:true})),...level.platforms.map(([x,y,w,solid=false])=>({x,y,w,h:solid?FLOOR-y:18,solid}))];this.hazards=level.hazards.map(([x,w])=>({x,w}));this.relays=level.relays.map(([x,y])=>({x,y,on:false}));
   document.querySelector('#upgrades').innerHTML='';ui.button.disabled=false;this.rewardPending=false;for(const a of this.actors||[]){a.sprite.destroy();a.roleLabel?.destroy()}this.actors=[];this.corpses=[];this.shots=[];this.particles=[];this.deaths=[];this.effects.clear();this.prompt?.setVisible(false);this.deathWait=0;this.mouseAim.down=false;this.transfers=0;this.kills=0;this.elapsed=0;this.reactor=0;this.transition=0;this.reinforced=false;const entry=this.levelIndex===0?{type:'vigia',hp:58}:(this.entryBody||{type:'sucata',hp:40});this.player=this.spawn(entry.type,175,500,true);this.player.hp=entry.hp;this.transfers=this.levelIndex===0?1:0;document.querySelector('#dialogue').hidden=true;
   for(const [type,x,y,role='normal'] of level.enemies){const a=this.spawn(type,x,y);a.role=role;if(role!=='normal')a.roleLabel=this.add.text(x,y-91,OUC.roles[role].label,{fontFamily:'monospace',fontSize:'10px',color:'#'+OUC.roles[role].color.toString(16).padStart(6,'0'),backgroundColor:'#08121a',padding:{x:3,y:2}}).setOrigin(.5).setDepth(15);a.windup=0;a.rush=0;a.aiCooldown=1.5;if(role==='warden'){a.hp=a.maxHp=145;this.boss=a}}if(this.levelIndex!==4)this.boss=null;
   this.drawBackdrop();this.drawWorld();this.cameras.main.scrollX=0;this.say(level.intro,9);this.updateHUD();document.querySelector('header b').textContent=`0${this.levelIndex+1} / ${level.name.toUpperCase()}`;
  };
  p.drawBackdrop=function(){const g=this.back,level=this.level||OUC.levels[0];g.clear();g.fillStyle(level.bg);g.fillRect(0,0,5000,620);
   for(let x=0;x<5000;x+=220){g.lineStyle(2,level.color,.13);g.strokeRect(x+20,135,170,320);g.fillStyle(level.color,.06);g.fillRect(x+25,140,160,310);
    if(level.kind==='archive'){for(let y=155;y<435;y+=27){g.fillStyle(level.color,.23);g.fillRect(x+40,y,130,3);g.fillRect(x+46,y+8,12,7)}}
    else if(level.kind==='furnace'){g.fillStyle(0xff693b,.13);g.fillTriangle(x+40,450,x+100,195,x+170,450);g.lineStyle(12,0x69453c);g.lineBetween(x+85,110,x+85,300)}
    else if(level.kind==='security'){g.lineStyle(2,level.color,.25);g.lineBetween(x+35,180,x+175,410);g.lineBetween(x+175,180,x+35,410)}
    else if(level.kind==='core'){g.lineStyle(2,level.color,.18);g.strokeEllipse(x+110,300,135,240);g.fillStyle(level.color,.3);g.fillRect(x+108,180,4,240)}
    else {g.fillStyle(level.color,.16);g.fillRect(x+58,175,94,120);g.fillRect(x+92,300,26,120)}
   }g.fillStyle(0x07101b,.45);g.fillRect(0,455,5000,165);
  };
  p.drawWorld=function(){base.drawWorld.call(this);const g=this.world,level=this.level||OUC.levels[0];for(const platform of this.platforms){g.fillStyle(level.color,.65);g.fillRect(platform.x,platform.y,platform.w,3)}if(level.kind==='core'){g.lineStyle(5,level.color,.25);g.strokeEllipse(3330,220,180,180);g.strokeEllipse(3330,220,135,135);g.fillStyle(level.color,.4);g.fillRect(3325,140,10,155)}};
  p.startDialogue=function(lines){this.dialogueLines=lines;this.dialogueIndex=0;this.state='dialogue';this.mouseAim.down=false;this.input.keyboard.resetKeys();document.querySelector('#dialogue').hidden=false;this.showDialogueLine()};
  p.showDialogueLine=function(){const [speaker,line]=this.dialogueLines[this.dialogueIndex];document.querySelector('#dialogue-speaker').textContent=speaker;document.querySelector('#dialogue-line').textContent=line;document.querySelector('#dialogue-next').textContent=this.dialogueIndex===this.dialogueLines.length-1?'CONTINUAR JOGO':'CONTINUAR';document.querySelector('#dialogue-count').textContent=(this.dialogueIndex+1)+' / '+this.dialogueLines.length;document.querySelector('#dialogue-next').focus()};
  p.nextDialogue=function(){if(this.state!=='dialogue')return;this.dialogueIndex++;if(this.dialogueIndex>=this.dialogueLines.length)this.closeDialogue();else this.showDialogueLine()};
  p.closeDialogue=function(){document.querySelector('#dialogue').hidden=true;this.state='play';this.input.keyboard.resetKeys();this.mouseAim.down=false};
  p.beginLevel=function(){this.reset();this.state='play';ui.overlay.style.display='none';this.showHUD(true);this.input.keyboard.resetKeys();Settings.syncMenu()};
  p.primary=function(){if(this.state==='win'&&this.rewardPending)return;if(this.state==='menu'){this.state='cinematic';ui.overlay.style.display='none';Cinematic.play(()=>this.beginLevel());return}if(this.state==='cinematic')return;if(this.state==='paused'){this.state='play';ui.overlay.style.display='none';return}if(this.state==='complete'){this.mainMenu();return}if(this.state==='win'){this.entryBody={type:this.player.type,hp:Math.min(this.player.maxHp,this.player.hp+20)};this.levelIndex++;}this.beginLevel()};
  p.mainMenu=function(){Cinematic.stop();this.upgrades=[];this.upgradeTier=0;this.entryBody=null;this.levelIndex=0;this.runStats={kills:0,transfers:0,time:0};this.reset();this.state='menu';this.showHUD(false);ui.overlay.style.display='flex';ui.eyebrow.textContent='INSTALAÇÃO N-01 · SEIS SETORES';ui.title.textContent='SINGULAR';ui.title.style.fontSize='';ui.story.innerHTML='Seu corpo ficou no núcleo.<br>A máquina que o roubou quer você de volta.';ui.brief.style.display='';ui.button.innerHTML='DESPERTAR <span>↗</span>';ui.hint.textContent='Campanha de game jam · melhorias entre fases · reinício por setor';Settings.syncMenu()};
  p.end=function(win,reason){if(['win','complete'].includes(this.state))return;this.mouseAim.down=false;this.state=win?'win':'dead';ui.overlay.style.display='flex';ui.title.style.fontSize='clamp(30px,5vw,65px)';ui.brief.style.display='none';ui.eyebrow.textContent=win?`0${this.levelIndex+1} / ${this.level.name.toUpperCase()} · CONCLUÍDO`:'NÚCLEO DESCONECTADO';ui.title.textContent=win?'Você continua.':'Sinal perdido.';ui.button.disabled=false;ui.button.innerHTML='TENTAR ESTA FASE <span>↻</span>';ui.story.textContent=reason||'';ui.hint.textContent='Reinicie esta fase com as melhorias que já conquistou.';
   if(win){this.runStats.kills+=this.kills;this.runStats.transfers+=this.transfers;this.runStats.time+=this.elapsed;if(this.levelIndex<OUC.levels.length-1)this.offerUpgrade();else{this.state='complete';ui.eyebrow.textContent='EPÍLOGO · APENAS UM';ui.title.textContent='Ainda sou eu.';ui.story.innerHTML='ECO silencia. Os arquivos ficam.<br>Nilo guarda a mensagem de Iara e atravessa a porta. O corpo humano não está mais lá. O mundo, talvez, ainda esteja.<br><br>— Eu deixo a luz acesa.<br><br>No peito de uma única máquina, o azul continua.';ui.hint.textContent=`5 setores · ${this.runStats.transfers} transferências · ${this.runStats.kills} inimigos · ${Math.floor(this.runStats.time/60)} min ${Math.floor(this.runStats.time%60)} s de jogo`;ui.button.innerHTML='VOLTAR AO INÍCIO <span>↗</span>';document.querySelector('#upgrades').innerHTML='';this.rewardPending=false}}else ui.story.textContent=reason+' Reinicie o setor. Preserve o corpo que deseja assumir e proteja o núcleo durante a recarga.';void 0;Settings.syncMenu();
  };
  p.offerUpgrade=function(){const chosen=this.upgrades[0],tier=this.upgradeTier||0,choices=R.upgrades.filter(u=>!chosen||u.id===chosen);this.rewardPending=tier<5;ui.title.textContent=chosen?'Apenas um. Mais forte.':'Escolha o que permanece.';ui.story.textContent=chosen?'Sua escolha continua. Reforce a mesma melhoria antes do próximo setor.':'Escolha uma única evolução para toda a campanha. Nos próximos setores, somente ela será aprimorada.';ui.button.disabled=this.rewardPending;ui.button.innerHTML='PRÓXIMO SETOR <span>↗</span>';ui.hint.textContent='Próximo: '+OUC.levels[this.levelIndex+1].name+' · O caminho escolhido acompanha todos os corpos.';document.querySelector('#upgrades').innerHTML=choices.map(u=>`<button class="upgrade" data-upgrade="${u.id}"><b>${u.label} · ${tier+1}/5</b><span>${chosen?u.effect(tier)+' → ':''}${u.effect(tier+1)}</span><small>${chosen?'Reforçar o caminho escolhido':u.description}</small></button>`).join('');document.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>this.chooseUpgrade(b.dataset.upgrade))};
  p.interact=function(){const player=this.player;for(const [i,r] of this.relays.entries())if(!r.on&&Math.abs(r.x-player.x)<65&&Math.abs(r.y-player.y)<55){r.on=true;this.drawWorld();this.burst(r.x,r.y-34,0x77e9e9,20);tone(760,.2,'sine');this.startDialogue(this.level.memory[i])}if(player.x>3450){if(!this.relays.every(r=>r.on))this.say('Ative os três terminais para liberar a porta.',4);else if(this.levelIndex===0&&this.transfers===0)this.say('A porta exige uma transferência: receba o golpe fatal de um autômato.',5);else if(this.boss?.alive&&!this.boss.controlled)this.say('Desative ou possua o Custódio para romper o último vínculo.',5);else this.end(true)}};
  p.updateHUD=function(){base.updateHUD.call(this);this.objective.setText(`0${(this.levelIndex||0)+1}/06 · ${(this.level||OUC.levels[0]).name.toUpperCase()}\n\nVÍNCULOS ${this.relays.filter(r=>r.on).length}/3 · TROCAS ${this.transfers}`)};
  p.aimVector=function(a){if(!a.controlled&&['sniper','warden','burst'].includes(a.role)){if(a.lockedAim)return a.lockedAim;const dx=this.player.x-a.x,dy=this.player.y-a.y,n=Math.hypot(dx,dy)||1;return {x:dx/n,y:dy/n}}return base.aimVector.call(this,a)};
  p.enemyAI=function(a,dt){if(!a.role||a.role==='normal'){base.enemyAI.call(this,a,dt);return}const dx=this.player.x-a.x,dy=this.player.y-a.y;a.face=dx<0?-1:1;a.aiCooldown=Math.max(0,a.aiCooldown-dt);
   if(a.role==='hunter'){if(a.rush>0){a.rush-=dt;a.vx=a.rushDir*340}else if(a.windup>0){a.vx=0;a.windup-=dt;if(a.windup<=0){a.rush=.48;a.rushDir=a.face;a.aiCooldown=1.7}}else{a.vx=Math.abs(dx)>65?a.face*95:0;if(Math.abs(dx)<300&&Math.abs(dy)<65&&a.aiCooldown<=0)a.windup=.55}if(Math.abs(dx)<75&&Math.abs(dy)<55)this.attack(a);if(a.ground&&dy< -60&&dy> -125&&Math.abs(dx)<180){a.vy=-550;a.ground=false}}
   else{a.vx=0;if(a.windup>0){a.windup-=dt;if(a.windup<=0){this.attack(a);a.lockedAim=null;a.aiCooldown=a.role==='warden'?1.1:a.role==='burst'?1.5:1.8}}else if(Math.abs(dx)<(a.role==='sniper'?650:550)&&Math.abs(dy)<270&&a.aiCooldown<=0&&a.attack<=0){a.lockedAim=null;a.lockedAim=this.aimVector(a);a.windup=a.role==='sniper'?.85:.65}}
   if(a.x+a.vx*dt<a.minX||a.x+a.vx*dt>a.maxX)a.vx=0;
  };
  p.attack=function(a){const before=this.shots.length;base.attack.call(this,a);if(!a.controlled&&['burst','warden'].includes(a.role)&&this.shots.length>before){const shot=this.shots.at(-1),angle=Math.atan2(shot.vy,shot.vx);for(const offset of [-.2,.2])this.shots.push({...shot,vx:Math.cos(angle+offset)*330,vy:Math.sin(angle+offset)*330})}if(!a.controlled&&a.role==='sniper'&&this.shots.length>before){const shot=this.shots.at(-1);shot.vx*=1.55;shot.vy*=1.55}};
  p.renderActors=function(dt){base.renderActors.call(this,dt);for(const a of this.actors){if(a.roleLabel)a.roleLabel.setPosition(a.x,a.y-91).setVisible(a.alive&&!a.controlled&&Math.abs(a.x-this.player.x)<620);if(a.alive&&!a.controlled)a.sprite.setTint(a.windup>0&&Math.floor(this.clock*12)%2?0xffffff:OUC.roles[a.role||'normal'].color)}};
  const effects=p.drawEffects;p.drawEffects=function(dt){effects.call(this,dt);const g=this.effects;for(const a of this.actors)if(a.alive&&!a.controlled&&a.windup>0){g.lineStyle(2,OUC.roles[a.role].color,.7);if(a.lockedAim)g.lineBetween(a.x,a.y-28,a.x+a.lockedAim.x*650,a.y-28+a.lockedAim.y*650);else{g.lineBetween(a.x,a.y-26,a.x+a.face*145,a.y-26);g.strokeEllipse(a.x,a.y-28,60,60)}}};
  p.startDash=function(a){const ok=base.startDash.call(this,a);if(ok&&this.upgrades.includes('mobility'))a.dashCooldown*=1-.08*R.upgradeLevel(this,'mobility');return ok};
  p.hit=function(a,damage,killer){const previous=this.player;base.hit.call(this,a,damage,killer);};
 }
};
