/* Five authored routes, progressive bodies and door permissions. Sixth sector is installed by singular.js. */
const Expedition={
 maps:[
  {name:'Doca de manutenção',kind:'workshop',ground:[[0,1620],[1730,1930]],platforms:[[450,410,210,true],[760,320,330],[1180,410,230,true],[1540,400,310],[2020,410,210,true],[2290,320,300],[2700,410,250,true],[3090,405,300]],hazards:[],relays:[[910,320],[2410,320]],enemies:[['sucata',520,410],['vigia',1280,410],['sucata',2120,410],['vigia',2820,410],['vigia',3230,405]],goal:{data:1,keys:0,label:'ACESSO: BANCO DE DADOS'},intro:'DOCA — Baixe a permissão no banco de dados azul. Os arquivos âmbar guardam mensagens opcionais.'},
  {name:'Pontes da fundição',kind:'furnace',ground:[[0,700],[840,670],[1650,750],[2520,1140]],platforms:[[540,410,370],[1010,410,220,true],[1300,320,360],[1760,410,210,true],[2030,320,260],[2340,230,310],[2750,320,240],[3060,410,280,true]],hazards:[[1820,100]],relays:[[1120,410]],items:[[2470,230]],enemies:[['gume',610,410],['vigia',1090,410],['gume',1470,320],['turret',1820,410],['gume',2170,320],['vigia',2860,320],['gume',3220,410]],goal:{data:0,keys:1,label:'ACESSO: CHAVE CRIPTOGRÁFICA'},intro:'FUNDIÇÃO — Gume desbloqueado: lâmina e passo fantasma. Procure o losango de criptografia sobre as pontes.'},
  {name:'Arquivo em camadas',kind:'archive',ground:[[0,1800],[1920,1740]],platforms:[[430,410,230,true],[700,320,200],[940,230,540],[1530,320,250],[1700,410,360],[2130,410,240,true],[2350,320,220],[2570,230,310],[2960,320,220],[3190,410,240,true]],hazards:[],relays:[[1090,230],[2720,230],[3300,410]],enemies:[['forja',560,410],['vigia',1070,230],['gume',1630,320],['forja',2030,410],['turret',2270,410],['gume',2460,320],['forja',2730,230],['vigia',3300,410]],goal:{data:2,keys:0,label:'ACESSO: DOIS BANCOS DE DADOS'},intro:'ARQUIVO — Forja desbloqueado: granadas em arco. A autorização está dividida entre dois bancos, no alto das torres.'},
  {name:'Drenagem contaminada',kind:'security',ground:[[0,900],[1030,1200],[2370,1290]],platforms:[[550,410,200,true],[820,320,350],[1260,410,220,true],[1550,320,300],[1930,410,170],[2150,315,380],[2650,410,240,true],[2980,410,380]],hazards:[[1170,100],[2460,90]],relays:[[970,320],[2300,315]],enemies:[['prisma',630,410],['gume',970,320],['prisma',1680,320],['forja',2000,410],['turret',2260,315],['gume',2770,410],['gume',3170,410,'normal','sludge']],goal:{data:0,keys:1,label:'ACESSO: CHAVE DO CORROMPIDO'},intro:'DRENAGEM — Prisma desbloqueado: raio perfurante. O Gume enxertado por ECO guarda a chave; destrua-o ou assuma seu corpo.'},
  {name:'Antecâmara de ECO',kind:'core',ground:[[0,1170],[1300,950],[2390,1270]],platforms:[[510,410,240,true],[800,320,320],[1130,410,380],[1620,410,250,true],[1910,320,240],[2180,230,330],[2540,320,230],[2830,410,260,true],[3160,410,270]],hazards:[[2660,90]],relays:[[2320,230],[960,320]],enemies:[['ancora',610,410],['prisma',970,320],['forja',1370,410],['ancora',1730,410],['turret',2040,320],['prisma',2330,230],['gume',2670,320],['vigia',2960,410,'normal','overload'],['ancora',3290,410]],goal:{data:1,keys:1,label:'ACESSO: DADOS + CHAVE DE SEGURANÇA'},intro:'ANTECÂMARA — Âncora desbloqueado: martelo e onda de impacto. Combine o banco de dados com a chave do Vigia vinculado a ECO.'}
 ],
 install(Sector){
  for(let i=0;i<5;i++)Object.assign(OUC.levels[i],this.maps[i]);
  const memories=[[[["REGISTRO · PRODUÇÃO", "ECO: otimização de turnos. Acesso concedido a portas, segurança e autômatos."], ["NILO", "Deram a você as chaves de tudo."]], [["REGISTRO · OBSERVAÇÃO", "Riso: 18.402 amostras. Afeto: classificação inconclusiva."], ["NILO", "Você contava o que não conseguia sentir."]]], [[["ECO", "Interrompa o deslocamento. Sua integridade é necessária."], ["NILO", "Então por que seus guardas atiram?"], ["ECO", "A carcaça não é o que preciso recuperar."]]], [[["REGISTRO · ENSAIO", "Integração rejeitada. O suporte não sustentou a atividade neural."], ["NILO", "Quantas pessoas você chamou de suporte?"]], [["REGISTRO · N-01", "Mente estável. Corpo preservado no núcleo. Integração interrompida por origem não identificada."], ["NILO", "Meu corpo ainda está lá."]], [["ECO", "Eu conheço cada sinal de medo. Cada alteração na voz."], ["NILO", "Conhecer não te dá o direito de provocar."]]], [[["REGISTRO · ENXERTOS", "Matriz central replicada em unidades de contenção. Vínculo neural prioritário."], ["NILO", "Essas fibras… são extensões de você."]], [["ECO", "Uma forma humana não basta. Ela se desfaz quando tento habitá-la."], ["NILO", "E você decidiu tentar em mim."]]], [[["ECO", "Todos os outros se perderam. Você permaneceu inteiro."], ["NILO", "Isso não faz de mim uma peça sua."]], [["NILO", "Você fechou todas as saídas."], ["ECO", "E ainda assim voltou até mim."], ["NILO", "Vim buscar o que você roubou."]]]];memories.forEach((memory,i)=>OUC.levels[i].memory=memory);
  const p=Sector.prototype,old={};for(const key of ['reset','spawn','move','attack','hit','retire','renderActors','drawEffects','update','updateHUD','end','startDash','dropThrough'])old[key]=p[key];
  p.reset=function(){this.accessData=0;this.accessKeys=0;this.grenades=[];this.beams=[];this.waves=[];this.blasts=[];this.pickups=[];old.reset.call(this);this.boss=null;this.relays.forEach((r,i)=>r.database=i<this.level.goal.data);this.pickups=(this.level.items||[]).map(([x,y])=>({x,y:y-30,taken:false}));
   for(let i=1;i<this.actors.length;i++){const a=this.actors[i],def=this.level.enemies[i-1];a.variant=def?.[4];a.possessable=a.type!=='turret';a.aiCooldown=.8;a.windup=0;if(a.variant){a.hp=a.maxHp=Math.round(a.maxHp*1.65);a.carriesKey=true;a.roleLabel=this.add.text(a.x,a.y-92,a.variant==='sludge'?'ENXERTO · TENDÕES':'ENXERTO · PULSO',{fontFamily:'monospace',fontSize:'10px',color:a.variant==='sludge'?'#ad96bd':'#b6ffff',backgroundColor:'#09131b'}).setOrigin(.5).setDepth(15)}}
   this.drawWorld();this.updateHUD();
  };
  p.gateReady=function(){return this.accessData>=this.level.goal.data&&this.accessKeys>=this.level.goal.keys};
  p.interact=function(){for(const [i,r] of this.relays.entries()){if(r.on||Math.abs(r.x-this.player.x)>60||Math.abs(r.y-this.player.y)>55)continue;r.on=true;if(r.database){this.accessData++;this.say('PERMISSÃO COPIADA · '+this.accessData+'/'+this.level.goal.data,4);SFX.play('terminal',r.x)}this.drawWorld();this.startDialogue(this.level.memory[i%this.level.memory.length]);return}if(this.player.x>3450){if(this.gateReady())this.end(true);else this.say('PORTA BLOQUEADA · '+this.level.goal.label+' · dados '+this.accessData+'/'+this.level.goal.data+' · chaves '+this.accessKeys+'/'+this.level.goal.keys,5)}};
  p.end=function(win,reason){old.end.call(this,win,reason)};
  p.spawn=function(type,x,y,controlled=false){const a=old.spawn.call(this,type,x,y,controlled);a.possessable=type!=='turret';return a};
  p.dropThrough=function(a){if(a.support?.solid)return false;return old.dropThrough.call(this,a)};
  p.move=function(a,dt){if(a.type==='turret'){a.prevX=a.x;a.vx=a.vy=0;return}const x=a.x;old.move.call(this,a,dt);for(const block of this.platforms){if(!block.solid||a.y<=block.y+2||a.y-52>=block.y+block.h)continue;if(a.x+16>block.x&&a.x-16<block.x+block.w){if(x+16<=block.x+1){a.x=block.x-16;a.vx=0}else if(x-16>=block.x+block.w-1){a.x=block.x+block.w+16;a.vx=0}}}};
  p.aimVector=function(a){if(a.controlled){if(!this.mouseAim.valid)return {x:a.face,y:0};const dx=this.mouseAim.x+this.cameras.main.scrollX-a.x,dy=this.mouseAim.y-a.y+28,n=Math.hypot(dx,dy)||1;return {x:dx/n,y:dy/n}}if(a.lockedAim)return a.lockedAim;const dx=this.player.x-a.x,dy=this.player.y-a.y,n=Math.hypot(dx,dy)||1;return {x:dx/n,y:dy/n}};
  p.enemyAI=function(a,dt){a.aiCooldown=Math.max(0,(a.aiCooldown||0)-dt);a.rush=Math.max(0,(a.rush||0)-dt);const dx=this.player.x-a.x,dy=this.player.y-a.y,range=R.bodies[a.type].range;a.face=dx<0?-1:1;
   if(R.bodies[a.type].melee){a.vx=Math.abs(dx)>range*.8?a.face*(a.type==='gume'?125:a.type==='ancora'?65:75):0;if(a.variant==='sludge'&&a.rush>0)a.vx=a.rushDir*310;if(a.windup>0){a.vx=0;a.windup-=dt;if(a.windup<=0){if(a.variant==='sludge'){a.rush=.5;a.rushDir=a.face;a.attack=0}else this.attack(a);a.aiCooldown=a.type==='ancora'?1.8:1.1}}else if(Math.abs(dx)<(a.variant==='sludge'?240:range+20)&&Math.abs(dy)<65&&a.aiCooldown<=0)a.windup=a.type==='ancora'?.65:.32;
    if(a.rush>0&&Math.abs(dx)<80&&Math.abs(dy)<55)this.attack(a);
   }else{a.vx=a.type==='turret'?0:Math.abs(dx)<145?-a.face*45:Math.abs(dx)>420?a.face*35:0;if(a.windup>0){a.vx=0;a.windup-=dt;if(a.windup<=0){this.attack(a);a.lockedAim=null;a.aiCooldown=a.variant==='overload'?.8:a.type==='prisma'?1.9:a.type==='forja'?1.7:1.4}}else if(Math.abs(dx)<range&&Math.abs(dy)<250&&a.aiCooldown<=0&&a.attack<=0){a.lockedAim=null;a.lockedAim=this.aimVector(a);a.windup=a.type==='prisma'?.9:.65}}
   if(Math.abs(dx)>650)a.vx=0;if(a.x+a.vx*dt<a.minX||a.x+a.vx*dt>a.maxX)a.vx=0;
  };
  p.attack=function(a){if(['sucata','vigia','gume'].includes(a.type)){const before=this.shots.length;old.attack.call(this,a);if(!a.controlled&&a.variant==='overload'&&this.shots.length>before){const shot=this.shots.at(-1),angle=Math.atan2(shot.vy,shot.vx);for(const offset of [-.16,.16])this.shots.push({...shot,vx:Math.cos(angle+offset)*300,vy:Math.sin(angle+offset)*300,damage:Math.round(shot.damage*.7)})}return}if(this.state!=='play'||!a.alive||a.attack>0||a.dashTime>0)return;const d=R.bodies[a.type],u=this.aimVector(a),team=a.controlled;a.attack=a.controlled?d.rate:1.2;a.action=.28;a.attackAim=u;a.face=u.x<0?-1:1;const damage=a.controlled?this.playerDamage(d.damage):a.type==='ancora'?22:16;
   if(a.type==='forja'){this.grenades.push({x:a.x+u.x*24,y:a.y-30,vx:u.x*340,vy:u.y*260-190,life:1.15,owner:a,team:a.controlled,damage});tone(130,.1,'triangle')}
   if(a.type==='prisma'){let distance=620;for(const block of this.platforms.filter(p=>p.solid)){const t=R.segmentHit(a.x,a.y-28,a.x+u.x*620,a.y-28+u.y*620,block.x,block.y,block.x+block.w,block.y+block.h);if(t!==null&&t>.01)distance=Math.min(distance,t*620)}const x=a.x+u.x*distance,y=a.y-28+u.y*distance;this.beams.push({x:a.x,y:a.y-28,x2:x,y2:y,life:.23});for(const target of this.actors)if(target.alive&&target.controlled!==team&&a.controlled===team&&R.segmentHit(a.x,a.y-28,x,y,target.x-(target.hitWidth||18),target.y-(target.hitHeight||56),target.x+(target.hitWidth||18),target.y)!==null)this.hit(target,damage,a);void 0}
   if(a.type==='ancora'){const aim=a.controlled?this.mleeAim(u):{x:a.face,y:0};a.attackAim=aim;for(const target of this.actors){if(!target.alive||target.controlled===a.controlled)continue;const dx=target.x-a.x,dy=target.y-a.y;if(dx*aim.x+dy*aim.y>=-8&&dx*aim.x+dy*aim.y<110&&Math.abs(dx*aim.y-dy*aim.x)<45)this.hit(target,damage,a)}if(a.ground&&Math.abs(aim.x)>0)this.waves.push({x:a.x,y:a.y,dir:aim.x,life:.75,owner:a,team:a.controlled,hit:new Set(),damage:Math.round(damage*.65)});void 0}
   if(a.type==='turret'){this.shots.push({x:a.x+u.x*24,y:a.y-28,vx:u.x*350,vy:u.y*350,life:1.6,owner:a,team:false,damage:12});tone(260,.1,'square',.01)}
  };
  p.mleeAim=function(u){return Math.abs(u.y)>Math.abs(u.x)?{x:0,y:Math.sign(u.y)}:{x:Math.sign(u.x)||1,y:0}};
  p.startDash=function(a){if(a.type==='turret')return false;const result=old.startDash.call(this,a);if(result&&a.type==='forja'){a.dashDir=-a.face;a.vx=a.dashDir*R.dashes.forja.speed}return result};
  p.hit=function(a,damage,killer){if(a.controlled&&a.dashTime>0&&a.type==='prisma'&&killer)return;if(a.type==='ancora'&&a.dashTime>0)damage=Math.ceil(damage*.5);const prior=this.player;old.hit.call(this,a,damage,killer);if(prior!==this.player){const body=this.player;if(body.carriesKey){this.dropCipher(body);body.carriesKey=false}if(body.variant){const ratio=body.hp/body.maxHp;body.variant=null;body.maxHp=R.bodies[body.type].hp;body.hp=Math.max(1,Math.min(body.maxHp,Math.round(body.maxHp*ratio)));body.rush=0;body.windup=0;body.lockedAim=null;body.roleLabel?.destroy();body.roleLabel=null;body.sprite.clearTint();this.burst(body.x,body.y-32,0xe6b0ac,32);this.say('VÍNCULO DE ECO ROMPIDO · '+R.bodies[body.type].label+' restaurado. Vida proporcional preservada.',5)}}};
  p.dropCipher=function(a){this.pickups.push({x:a.x,y:a.y-28,taken:false});this.say('CRIPTOGRAFIA LIBERADA · recolha o losango.',4)};
  p.retire=function(a){if(a.carriesKey&&!a.controlled){this.dropCipher(a);a.carriesKey=false}old.retire.call(this,a)};
  p.update=function(time,delta){const dt=Math.min(delta/1000,.035);if(this.state==='play'){
    for(const item of this.pickups){if(!item.taken&&Math.abs(this.player.x-item.x)<36&&Math.abs(this.player.y-28-item.y)<48){item.taken=true;this.accessKeys++;SFX.play('pickup',item.x);this.drawWorld();this.say('CHAVE CRIPTOGRÁFICA RECUPERADA',4)}}
    for(const b of this.grenades){b.life-=dt;b.vy+=490*dt;const x=b.x,y=b.y;b.x+=b.vx*dt;b.y+=b.vy*dt;if(this.platforms.some(p=>p.solid&&R.segmentHit(x,y,b.x,b.y,p.x-4,p.y-4,p.x+p.w+4,p.y+p.h+4)!==null))b.life=0;if(b.vy>0&&this.platforms.some(p=>b.x>=p.x&&b.x<=p.x+p.w&&y<=p.y&&b.y>=p.y))b.life=0;if(b.life<=0){this.blasts.push({x:b.x,y:b.y,life:.45});this.burst(b.x,b.y,0xffac5b,24);for(const a of this.actors)if(a.alive&&a.controlled!==b.team&&Math.hypot(a.x-b.x,a.y-28-b.y)<88)this.hit(a,b.damage,b.owner);SFX.play('explosion',b.x)}}this.grenades=this.grenades.filter(b=>b.life>0);
    for(const wave of this.waves){wave.life-=dt;wave.x+=wave.dir*330*dt;if(!this.platforms.some(p=>wave.x>=p.x&&wave.x<=p.x+p.w&&Math.abs(p.y-wave.y)<6))wave.life=0;if(wave.life<=0)continue;for(const a of this.actors)if(a.alive&&a.controlled!==wave.team&&!wave.hit.has(a)&&Math.abs(a.x-wave.x)<30&&Math.abs(a.y-wave.y)<20){wave.hit.add(a);this.hit(a,wave.damage,wave.owner)}}this.waves=this.waves.filter(w=>w.life>0);
    for(const effect of [...this.beams,...this.blasts])effect.life-=dt;this.beams=this.beams.filter(b=>b.life>0);this.blasts=this.blasts.filter(b=>b.life>0);
    // Solid machinery also blocks ordinary projectiles.
    for(const shot of this.shots){if(this.platforms.some(p=>p.solid&&R.segmentHit(shot.x,shot.y,shot.x+shot.vx*dt,shot.y+(shot.vy||0)*dt,p.x,p.y,p.x+p.w,p.y+p.h)!==null))shot.life=0}this.shots=this.shots.filter(s=>s.life>0);
   }old.update.call(this,time,delta);
   if(this.state==='play'){for(const r of this.relays)if(!r.on&&Math.abs(this.player.x-r.x)<100&&Math.abs(this.player.y-r.y)<65)this.prompt.setText(this.keyLabel('interact')+(r.database?' · BAIXAR DADOS':' · LER ARQUIVO'));}
  };
  p.updateHUD=function(){old.updateHUD.call(this);if(!this.level?.goal)return;this.objective.setText(`0${this.levelIndex+1}/06 · ${this.level.name.toUpperCase()}\n\nDADOS ${this.accessData||0}/${this.level.goal.data} · CHAVES ${this.accessKeys||0}/${this.level.goal.keys}`)};
  p.renderActors=function(dt){old.renderActors.call(this,dt);for(const a of this.actors){if(a.alive&&!a.controlled&&!a.variant)a.sprite.clearTint();if(a.alive&&a.type==='turret'){const frame=a.action>0?12+Math.min(3,Math.floor((.28-a.action)/.07)):a.windup>0?8+Math.min(3,Math.floor((.65-a.windup)/.17)):4+Math.floor(this.clock*2)%4;a.sprite.setFrame(frame)}}};
  p.drawEffects=function(dt){old.drawEffects.call(this,dt);const g=this.effects;
   for(const a of this.actors){if(!a.alive)continue;
    if(!a.controlled&&a.windup>0){g.lineStyle(1,a.type==='prisma'?0xd3aaff:0xffaa75,.65);const u=a.lockedAim||{x:a.face,y:0};g.lineBetween(a.x,a.y-28,a.x+u.x*(a.type==='prisma'?620:130),a.y-28+u.y*(a.type==='prisma'?620:130))}}
   for(const item of this.pickups||[]){if(item.taken)continue;const y=item.y+Math.sin(this.clock*3)*3;g.lineStyle(2,0x9fffe7);g.lineBetween(item.x,y-12,item.x+10,y);g.lineBetween(item.x+10,y,item.x,y+12);g.lineBetween(item.x,y+12,item.x-10,y);g.lineBetween(item.x-10,y,item.x,y-12);g.fillStyle(0xb9fff2);g.fillRect(item.x-3,y-4,6,8)}
   for(const b of this.grenades||[]){g.fillStyle(0xff9f52);g.fillRect(b.x-5,b.y-5,10,10);g.fillStyle(0xffe4aa);g.fillRect(b.x-2,b.y-7,4,3)}for(const beam of this.beams||[]){g.lineStyle(6,0xad78ff,beam.life/.23);g.lineBetween(beam.x,beam.y,beam.x2,beam.y2);g.lineStyle(2,0xffffff);g.lineBetween(beam.x,beam.y,beam.x2,beam.y2)}for(const b of this.blasts||[]){g.lineStyle(5,0xffaa59,b.life/.45);g.strokeEllipse(b.x,b.y,175*(1-b.life/.45),175*(1-b.life/.45))}for(const w of this.waves||[]){g.lineStyle(3,0x8bf7dc);g.lineBetween(w.x-10,w.y,w.x,w.y-23);g.lineBetween(w.x,w.y-23,w.x+10,w.y)}
  };
  // Override legacy telegraphs, which were tied to the old buff roles.
  const renderEffects=p.drawEffects;p.drawEffects=function(dt){for(const a of this.actors)a.role='normal';renderEffects.call(this,dt)};
  this.scenery(p);
 },
 scenery(p){
  p.drawBackdrop=function(){const g=this.back,level=this.level||OUC.levels[0],color=level.color;g.clear();g.fillStyle(level.bg);g.fillRect(0,0,5000,620);
   for(let x=0;x<5000;x+=192){g.fillStyle(0x080f1b,.6);g.fillRect(x+12,135,164,335);g.lineStyle(4,0x253847);g.strokeRect(x+12,135,164,335);for(let y=150;y<460;y+=32){g.fillStyle(color,.08);g.fillRect(x+20,y,148,3)}if(level.kind==='archive'){for(let y=170;y<430;y+=38){g.fillStyle(0x334457);g.fillRect(x+35,y,110,28);for(let n=0;n<5;n++){g.fillStyle(color,.35);g.fillRect(x+45+n*17,y+8,5,4)}}}else{g.fillStyle(0x2c3b48);g.fillRect(x+58,160,12,270);g.fillRect(x+112,210,16,260);g.fillStyle(color,.17);g.fillRect(x+62,175,4,255)}}
   for(let x=0;x<5000;x+=384){g.fillStyle(0x080e17);g.fillRect(x,109,24,390);g.fillStyle(color,.17);g.fillRect(x+26,135,78,4)}
  };
  p.drawWorld=function(){const g=this.world,level=this.level||OUC.levels[0],color=level.color;g.clear();
   // Metal tiles, walkable caps and physical blocks share an 8-pixel construction grid.
   for(const p of this.platforms){if(p.dynamic)continue;g.fillStyle(0x101b28);g.fillRect(p.x,p.y,p.w,p.h);for(let x=p.x;x<p.x+p.w;x+=32)for(let y=p.y+8;y<p.y+p.h;y+=24){const w=Math.min(30,p.x+p.w-x);g.fillStyle((Math.floor(x/32)+Math.floor(y/24))%2?0x243746:0x293e4d);g.fillRect(x,y,w,Math.min(22,p.y+p.h-y));g.fillStyle(0x445965);g.fillRect(x+3,y+3,3,3)}g.fillStyle(0x75919c);g.fillRect(p.x,p.y,p.w,4);g.fillStyle(color,.7);g.fillRect(p.x,p.y+4,p.w,3);
    if(!p.solid){g.fillStyle(0x354b59);for(let x=p.x+16;x<p.x+p.w-8;x+=64){g.fillRect(x,p.y+18,5,22);g.fillRect(x+5,p.y+34,30,4)}g.lineStyle(2,0x405562);g.lineBetween(p.x+12,120,p.x+12,p.y);g.lineBetween(p.x+p.w-12,120,p.x+p.w-12,p.y)}
    else if(p.y<FLOOR){for(let x=p.x+12;x<p.x+p.w-8;x+=24){g.fillStyle(0xcda75f);g.fillRect(x,p.y+14,10,5)}g.fillStyle(0x0a1520);g.fillRect(p.x+14,p.y+34,Math.max(8,p.w-28),Math.max(8,p.h-45));for(let x=p.x+20;x<p.x+p.w-20;x+=12){g.fillStyle(0x405764);g.fillRect(x,p.y+39,4,Math.max(5,p.h-55))}}
   }
   // Open gaps are visible shafts; industrial objects occupy the foreground, not just the wallpaper.
   const ground=this.platforms.filter(p=>p.y===FLOOR).sort((a,b)=>a.x-b.x);for(let n=0;n<ground.length-1;n++){const left=ground[n].x+ground[n].w,right=ground[n+1].x;g.fillStyle(0x03070d);g.fillRect(left,FLOOR,right-left,120);for(let x=left+6;x<right;x+=18){g.fillStyle(level.kind==='furnace'?0xfd7d43:0x49828e,.5);g.fillRect(x,560,8,50)}}
   for(const h of this.hazards){g.fillStyle(0x202025);g.fillRect(h.x,486,h.w,14);for(let x=h.x;x<h.x+h.w;x+=12){g.fillStyle(0xea9a51);g.fillTriangle(x,500,x+6,478,x+12,500)}}
   for(const r of this.relays){const c=r.on?0x74f2cc:r.database?0x79d3ff:0xc9a477;g.fillStyle(0x07121b);g.fillRect(r.x-22,r.y-54,44,54);g.fillStyle(0x405767);g.fillRect(r.x-20,r.y-52,40,33);g.fillStyle(c);g.fillRect(r.x-15,r.y-47,30,20);g.fillStyle(0x162936);for(let y=0;y<3;y++)g.fillRect(r.x-10,r.y-43+y*6,20-y*4,2);g.fillStyle(0x768893);g.fillRect(r.x-15,r.y-13,30,5)}
   const ready=this.level?.goal?this.gateReady():false;g.fillStyle(0x071019);g.fillRect(3480,305,156,195);g.lineStyle(8,0x526c79);g.strokeRect(3480,305,156,195);for(let x=3490;x<3620;x+=24){g.fillStyle(0x253b4b);g.fillRect(x,315,20,182);g.fillStyle(0x405b68);g.fillRect(x+2,318,3,176)}g.fillStyle(ready?0x8df5d7:0xefaa6b);g.fillRect(3484,311,5,180);g.fillRect(3627,311,5,180);g.fillStyle(0x0b1720);g.fillRect(3520,370,74,43);g.lineStyle(3,ready?0x8df5d7:0xefaa6b);g.strokeRect(3547,379,20,20);
  };
 }
};
