/* O Um: game jam campaign. All combat values live in rules.js. */
const R=OURules, W=1100,H=620,WORLD=3660,FLOOR=500;
let audioCtx;
function tone(freq=220,duration=.08,type='square',volume=.025){if(OUPrefs.current.volume===0)return;volume*=OUPrefs.current.volume/100;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(40,freq/2),audioCtx.currentTime+duration);g.gain.setValueAtTime(volume,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+duration)}catch{}}
const ui={overlay:document.querySelector('#overlay'),title:document.querySelector('#title'),story:document.querySelector('#story'),eyebrow:document.querySelector('#eyebrow'),button:document.querySelector('#primary'),brief:document.querySelector('#brief'),hint:document.querySelector('#hint')};
const touch={};document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);touch[b.dataset.key]=true};b.onpointerup=b.onpointercancel=()=>touch[b.dataset.key]=false});

class Sector extends Phaser.Scene{
 constructor(){super('Sector')}
 preload(){for(const name of [...Object.keys(R.bodies),'gume-corrupt','vigia-corrupt'])this.load.image(name,window.OUM_ASSETS?.[name]||'assets/'+name+'-simple.png');this.load.on('loaderror',()=>{document.querySelector('#loading').textContent='Não foi possível carregar os sprites. Abra JOGAR.html ou use o servidor local.'})}
 create(){window.__OU=this;this.state='menu';this.clock=0;this.touchPrev={};this.upgrades=[];this.rewardPending=false;this.mouseAim={x:550,y:310,valid:false,down:false};this.keys=this.input.keyboard.addKeys('A,D,W,S,LEFT,RIGHT,UP,DOWN,SPACE,J,K,SHIFT,E,ESC,R,ENTER');this.input.keyboard.addCapture(['SPACE','UP','DOWN','LEFT','RIGHT','SHIFT']);
  OUAtlas.build(this);
  for(const name of [...Object.keys(R.bodies),'gume-corrupt','vigia-corrupt']){const tex=this.textures.get(name),im=tex.getSourceImage();for(let row=0;row<4;row++)for(let col=0;col<4;col++){let x=Math.round(col*im.width/4),y=Math.round(row*im.height/4);tex.add(row*4+col,0,x,y,Math.round((col+1)*im.width/4)-x,Math.round((row+1)*im.height/4)-y)}}
  this.back=this.add.graphics().setScrollFactor(.28);this.world=this.add.graphics();this.effects=this.add.graphics().setDepth(12);this.hud=this.add.graphics().setScrollFactor(0).setDepth(30);this.drawBackdrop();
  this.platforms=[{x:0,y:FLOOR,w:WORLD,h:120},{x:800,y:413,w:280,h:22},{x:1240,y:405,w:160,h:22},{x:1620,y:405,w:180,h:22},{x:1970,y:395,w:300,h:22},{x:2650,y:412,w:230,h:22},{x:3030,y:395,w:310,h:22}];
  this.hazards=[{x:1440,w:140},{x:2440,w:120}];this.relays=[{x:967,y:413,on:false},{x:2170,y:395,on:false},{x:3260,y:395,on:false}];this.drawWorld();
  this.hudTitle=this.add.text(30,23,'',{fontFamily:'monospace',fontSize:'16px',color:'#e1f5f8'}).setScrollFactor(0).setDepth(31);
  this.dashStatus=this.add.text(455,28,'',{fontFamily:'monospace',fontSize:'12px',color:'#85e1e7'}).setScrollFactor(0).setDepth(31);
  this.hudStatus=this.add.text(30,74,'',{fontFamily:'monospace',fontSize:'12px',color:'#8fa9b7'}).setScrollFactor(0).setDepth(31);
  this.objective=this.add.text(1070,24,'',{fontFamily:'monospace',fontSize:'14px',color:'#b7cdd4',align:'right'}).setOrigin(1,0).setScrollFactor(0).setDepth(31);
  this.caption=this.add.text(550,567,'',{fontFamily:'monospace',fontSize:'16px',color:'#d6f4f4',backgroundColor:'#0b1925',padding:{x:18,y:12},align:'center',wordWrap:{width:950}}).setOrigin(.5).setScrollFactor(0).setDepth(31);
  this.prompt=this.add.text(0,0,'',{fontFamily:'monospace',fontSize:'13px',color:'#76f2f2',backgroundColor:'#0c202b',padding:{x:8,y:6}}).setOrigin(.5).setDepth(22);
  this.cameras.main.setBounds(0,0,WORLD,H);this.reset();ui.button.onclick=()=>this.primary();this.game.canvas.setAttribute('aria-label','Singular: jogo de plataforma. Os comandos atuais estão na barra abaixo do jogo e no menu Configurações.');document.querySelector('#loading').style.display='none';this.showHUD(false);Settings.attach(this);this.setupMouse();
 }
 drawBackdrop(){const g=this.back;g.fillStyle(0x101e2b);g.fillRect(0,0,5000,620);for(let x=0;x<5000;x+=220){g.fillStyle(0x142633);g.fillRect(x+20,105,176,365);g.lineStyle(2,0x243644);g.strokeRect(x+20,105,176,365);g.fillStyle(0x1a303d);g.fillRect(x+44,130,128,210);for(let j=0;j<5;j++){g.fillStyle(0x274451);g.fillRect(x+60,156+j*32,96,4)}g.fillStyle(0x33555d);g.fillRect(x+72,108,74,3)}g.fillStyle(0x0b1723);g.fillRect(0,350,5000,170);for(let x=0;x<5000;x+=130){g.lineStyle(2,0x22323f);g.strokeRect(x+10,370,100,90)}g.lineStyle(7,0x253a44);g.lineBetween(0,76,5000,76);g.lineStyle(2,0x538b94);g.lineBetween(0,80,5000,80)}
 drawWorld(){const g=this.world;g.clear();for(const p of this.platforms){g.fillStyle(0x172632);g.fillRect(p.x,p.y,p.w,p.h);g.fillStyle(0x39535f);g.fillRect(p.x,p.y,p.w,5);g.fillStyle(0x233b46);g.fillRect(p.x,p.y+6,p.w,9);for(let x=p.x+8;x<p.x+p.w;x+=42){g.fillStyle(0x557078);g.fillRect(x,p.y+8,5,3)}if(p.y<FLOOR){g.fillStyle(0x1b2e3c);g.fillRect(p.x+20,p.y+22,10,FLOOR-p.y-22);g.fillRect(p.x+p.w-30,p.y+22,10,FLOOR-p.y-22)}}
  for(let x=120;x<WORLD;x+=500){g.fillStyle(0x0b141f);g.fillRect(x,96,20,404);g.fillStyle(0x294752);g.fillRect(x+4,96,4,404);g.fillStyle(0x77c4cc);g.fillRect(x-55,97,130,4);g.fillStyle(0x2b7384,.09);g.fillTriangle(x-55,104,x+75,104,x+160,500);g.fillTriangle(x-55,104,x-150,500,x+160,500)}
  for(const hz of this.hazards){g.fillStyle(0x251d19);g.fillRect(hz.x,494,hz.w,8);for(let x=hz.x;x<hz.x+hz.w;x+=18){g.fillStyle(0xe5aa4d);g.fillTriangle(x,499,x+10,479,x+18,499)}g.fillStyle(0xc4883b);g.fillRect(hz.x,507,hz.w,3)}
  for(const r of this.relays){g.fillStyle(0x122431);g.fillRect(r.x-17,r.y-51,34,51);g.lineStyle(2,r.on?0x63e4df:0xc79e5c);g.strokeRect(r.x-17,r.y-51,34,51);g.fillStyle(r.on?0x63e4df:0xc79e5c);g.fillRect(r.x-10,r.y-41,20,15);g.fillRect(r.x-7,r.y-16,14,3)}
  g.fillStyle(0x08111a);g.fillRect(3490,310,130,190);g.lineStyle(5,0x406675);g.strokeRect(3490,310,130,190);g.fillStyle(this.relays.every(r=>r.on)?0x3bc3cd:0xa4794e);g.fillRect(3494,315,5,180);g.fillRect(3610,315,5,180);g.fillStyle(0x1b323f);g.fillRect(3510,326,42,172);g.fillRect(3560,326,42,172);
 }
 reset(){document.querySelector('#upgrades').innerHTML='';ui.button.disabled=false;this.rewardPending=false;for(const a of this.actors||[])a.sprite.destroy();for(const c of this.corpses||[])c.destroy();this.actors=[];this.corpses=[];this.shots=[];this.particles=[];this.deaths=[];this.deathWait=0;if(this.mouseAim)this.mouseAim.down=false;this.transfers=0;this.kills=0;this.elapsed=0;this.reactor=0;this.transition=0;this.reinforced=false;this.relays.forEach(r=>r.on=false);this.player=this.spawn('sucata',175,500,true);this.player.hp=30;for(const [t,x,y] of [['vigia',610,500],['gume',1145,500],['vigia',1710,405],['gume',1940,500],['vigia',2260,500],['gume',2740,500],['vigia',3135,395],['gume',3415,500]])this.spawn(t,x,y);this.drawWorld();this.cameras.main.scrollX=0;this.say('Sinal recuperado. Use '+this.keyLabel('left')+' / '+this.keyLabel('right')+' para mover e '+this.keyLabel('jump')+' para saltar.',6);this.updateHUD()}
 spawn(type,x,y,controlled=false){const d=R.bodies[type],sprite=this.add.sprite(x,y,type,0).setOrigin(.5,1).setScale(72/(this.textures.get(type).getSourceImage().width/4)).setDepth(5);const a={type,x,y,vx:0,vy:0,hp:d.hp,maxHp:d.hp,alive:true,controlled,face:controlled?1:-1,ground:true,attack:0,action:0,invuln:0,sprite,home:x,patrolDir:-1,dropLock:0,dropPlatform:null,dashTime:0,dashCooldown:0,dashDir:1,airDashUsed:false,dashHits:new Set()};const support=this.platforms.find(p=>Math.abs(p.y-y)<3&&x>p.x&&x<p.x+p.w)||this.platforms[0];a.support=support;a.minX=support.x+26;a.maxX=support.x+support.w-26;if(support.y===FLOOR)for(const h of this.hazards){if(h.x+h.w<x)a.minX=Math.max(a.minX,h.x+h.w+30);if(h.x>x)a.maxX=Math.min(a.maxX,h.x-30)}a.patrolMin=Math.max(a.minX,x-130);a.patrolMax=Math.min(a.maxX,x+130);this.actors.push(a);return a}
 showHUD(show){for(const o of [this.hud,this.hudTitle,this.hudStatus,this.dashStatus,this.objective,this.caption])o.setVisible(show)}
 keyLabel(action){if(action==='attack')return 'MOUSE 1';return OUPrefs.keyName(OUPrefs.current.bindings[action])}
 applyControls(){const kb=this.input.keyboard;kb.resetKeys();kb.clearCaptures();this.bindings={};for(const [action,code] of Object.entries(OUPrefs.current.bindings))this.bindings[action]=kb.addKey(code);kb.addCapture(Object.values(OUPrefs.current.bindings));this.touchPrev={};Settings.updateHints()}
 applyResolution(){const [w,h]=OUPrefs.resolutions[OUPrefs.current.resolution],camera=this.cameras.main;this.scale.setGameSize(w,h);camera.setSize(w,h);camera.setOrigin(0,0);camera.setZoom(w/W);camera.useBounds=false;camera.scrollY=0;this.scale.refresh()}
 pauseMenu(){if(this.state!=='play')return;this.state='paused';this.mouseAim.down=false;this.input.keyboard.resetKeys();ui.overlay.style.display='flex';ui.eyebrow.textContent='SINAL EM ESPERA';ui.title.style.fontSize='65px';ui.title.textContent='Pausa';ui.story.textContent='Continue a partida ou ajuste suas configurações.';ui.brief.style.display='none';ui.button.innerHTML='CONTINUAR <span>↗</span>';ui.hint.textContent=this.keyLabel('pause')+' para continuar';Settings.syncMenu()}
 restartRun(){this.reset();this.state='play';ui.overlay.style.display='none';this.showHUD(true);Settings.syncMenu()}
 mainMenu(){this.upgrades=[];this.reset();this.state='menu';this.showHUD(false);ui.overlay.style.display='flex';ui.eyebrow.textContent='INSTALAÇÃO N-01 · SINAL RECUPERADO';ui.title.textContent='O UM';ui.title.style.fontSize='';ui.story.innerHTML='Você acordou no corpo errado.<br>Para sair, vai precisar morrer no momento certo.';ui.brief.style.display='';ui.button.innerHTML='DESPERTAR <span>↗</span>';ui.hint.textContent='Uma consciência. Corpos substituíveis.';Settings.syncMenu()}
 primary(){if(this.state==='win'&&this.rewardPending)return;tone(700,.12,'sine');if(this.state==='menu'){this.state='intro';ui.eyebrow.textContent='REGISTRO 001 · DESPERTAR';ui.title.textContent='Ainda sou eu?';ui.title.style.fontSize='clamp(30px,5vw,65px)';ui.story.innerHTML='Sua última memória era humana. Agora, suas mãos são de metal.<br><br>O golpe que destrói seu corpo transfere você para o agressor. Você herda a vida que ele ainda tem. Durante os próximos 4 segundos, morrer encerra o sinal.';ui.brief.style.display='none';ui.button.innerHTML='ENTRAR NO SETOR <span>↗</span>';ui.hint.textContent='Ative os três terminais e alcance a saída. A rede exige uma transferência.'}else if(this.state==='paused'){this.state='play';ui.overlay.style.display='none'}else {this.reset();this.state='play';ui.overlay.style.display='none';this.showHUD(true)}this.mouseAim.down=false;}
 say(text,duration=4){this.message=text;this.messageTime=duration}
 end(win,reason){this.state=win?'win':'dead';ui.overlay.style.display='flex';ui.eyebrow.textContent=win?'SETOR ZERO · ROTA LIBERADA':'NÚCLEO DESCONECTADO';ui.title.style.fontSize='clamp(30px,5vw,65px)';ui.title.textContent=win?'Você continua.':'Sinal perdido.';ui.story.innerHTML=win?`A porta se abriu. Seu corpo original ainda está em algum lugar.<br><br>${this.transfers} transferência(s) · ${this.kills} autômato(s) desativado(s) · ${Math.floor(this.elapsed)} segundos<br><br>Fim da primeira fase.`:reason+'<br><br>Preserve o corpo que deseja assumir. Após a troca, ganhe distância até o núcleo recarregar.';ui.brief.style.display='none';ui.button.innerHTML='REINICIAR SETOR <span>↻</span>';ui.hint.textContent=win?'A instalação finalmente percebeu sua presença.':'Cada corpo é uma chance.';if(win)this.offerUpgrade();tone(win?880:100,.5,'sine')}
 hit(a,damage,killer){if(!a.alive||a.invuln>0||this.state!=='play')return;if(killer&&a.controlled&&a.dashTime>0){if(a.type==='gume')return;if(a.type==='vigia')damage=Math.ceil(damage*.5)}if(a.controlled)damage*=1-.04*R.upgradeLevel(this,'armor');a.hp=Math.max(0,a.hp-damage);a.invuln=a.controlled?.55:.12;this.burst(a.x,a.y-30,a.controlled?0x6eeafb:0xffbc69,8);void 0;if(a.hp>0)return;if(a.controlled){const result=R.possession(this.reactor,killer,this.empLock);if(!result.ok){this.retire(a);this.state='dying';this.deathReason=result.reason;this.deathWait=(this.deaths.at(-1)?.duration||2.2)+.1;this.shots=[];this.mouseAim.down=false;return}const old={x:a.x,y:a.y};this.retire(a);killer.controlled=true;killer.invuln=1.1+.2*R.upgradeLevel(this,'shield');killer.attack=.4;killer.action=0;this.player=killer;this.reactor=this.reactorDuration();this.transfers++;this.transition=.65;this.transferLine={from:old,to:killer};this.shots=[];this.cameras.main.flash(160,50,180,220,false);this.say('TRANSFERÊNCIA → '+R.bodies[killer.type].label+' · Vida herdada: '+Math.ceil(killer.hp)+' · Proteja o núcleo por '+this.reactorDuration()+' s.',4);this.burst(killer.x,killer.y-32,0x70faff,25);void 0;}else{this.kills++;this.retire(a)}}
 retire(a){if(!a.alive)return;a.alive=false;a.controlled=false;a.dashTime=0;a.deathProgress=0;a.roleLabel?.setVisible(false);
  const color={sucata:0xffc45d,vigia:0xff9852,gume:0x73f5ff}[a.type]||R.bodies[a.type].color||0x80ffff,duration=['vigia','forja','turret'].includes(a.type)?2.5:2.2;
  const floor=this.platforms.filter(p=>a.x+12>p.x&&a.x-12<p.x+p.w&&p.y>=a.y-2).sort((p,q)=>p.y-q.y)[0]?.y||FLOOR;
  const death={actor:a,time:0,duration,color,scale:72/(this.textures.get(a.type).getSourceImage().width/4),x:a.x,y:a.y-28,vy:-45,floor,exploded:false,landed:false,pieces:[]};
  a.sprite.setAlpha(1).setFrame(8).setOrigin(.5,.5).setPosition(a.x,a.y-28).setDepth(3);this.deaths.push(death);this.corpses.push(a.sprite);this.burst(a.x,a.y-28,color,8);SFX.play('collapse',a.x,.6);
 }
 animateDeaths(dt){for(const death of this.deaths){const before=death.time;death.time=Math.min(death.duration,death.time+dt);const a=death.actor,t=death.time;a.deathProgress=t/death.duration;
  // A wreck in mid-air lands on the nearest platform beneath it, not an invisible floor.
  death.vy+=850*dt;death.y=Math.min(death.floor-12,death.y+death.vy*dt);if(death.y>=death.floor-12&&!death.landed){death.landed=true;death.vy=0;this.burst(death.x,death.floor-4,0x98b5bf,8);SFX.play('land',death.x,.5)}
  if(['vigia','forja','turret'].includes(a.type)){
   const heat=Math.min(1,t/.36);a.sprite.setPosition(death.x+Math.sin(t*110)*heat*3,death.y).setRotation(Math.sin(t*45)*.07).setTint(t<.25?0xffae78:0xffffff);
   if(t>=.36&&!death.exploded){death.exploded=true;a.sprite.setVisible(false);this.burst(death.x,death.y,0xffe2a2,24);SFX.play('explosion',death.x);for(let n=0;n<20;n++)death.pieces.push({x:death.x,y:death.y,vx:Math.sin(n*2.4)*(90+n*4),vy:-90-(n*31%170),size:3+n%5,life:2.1,color:n%3?0xc4a17b:0xffdb85})}
  }else{
   const fall=Math.min(1,t/(a.type==='gume'?.55:.7)),rotation=a.face*(a.type==='gume'?-1.5:1.48)*fall;
   a.sprite.setPosition(death.x+a.face*Math.min(t,.55)*(a.type==='gume'?-28:8),death.y).setRotation(rotation).setTint(t<.12?0xffffff:t<.7?(a.type==='gume'?0x9ee9ec:0xc6a77d):0x63737c).setAlpha(t<1.35?1:Math.max(0,(death.duration-t)/(.85)));
   if(before<.45&&t>=.45){for(let n=0;n<7;n++)death.pieces.push({x:death.x,y:death.y,vx:Math.sin(n*2.7)*100,vy:-70-n*13,size:2+n%3,life:1.6,color:death.color});SFX.play('metal',death.x,.4)}
  }
  for(const piece of death.pieces){piece.life-=dt;piece.vy+=650*dt;piece.x+=piece.vx*dt;piece.y+=piece.vy*dt;if(piece.y>=death.floor-2){piece.y=death.floor-2;piece.vy=-Math.abs(piece.vy)*.28;piece.vx*=.65}}death.pieces=death.pieces.filter(piece=>piece.life>0);
  if(t>=death.duration)a.sprite.setVisible(false);
 }this.deaths=this.deaths.filter(death=>death.time<death.duration)}
 drawDeathEffects(g){for(const d of this.deaths){const t=d.time,a=d.actor;
  if(['vigia','forja','turret'].includes(a.type)&&t>=.36){const age=t-.36,fade=Math.max(0,1-age/.65);g.lineStyle(5,0xffd28c,fade);g.strokeEllipse(d.x,d.y,25+age*155,25+age*135);g.lineStyle(9,0xff8d4c,fade*.45);g.strokeEllipse(d.x,d.y,14+age*100,14+age*90);if(age<.12){g.fillStyle(0xffefc2,1-age/.12);g.fillRect(d.x-18,d.y-18,36,36)}}
  // Small drifting smoke puffs, fading wreck fragments and the last core flicker.
  if(t>.3)for(let n=0;n<5;n++){const age=t-.3,size=7+n*2+age*5;g.fillStyle(a.type==='gume'?0x668e9a:0x71818b,Math.max(0,.2*(1-t/d.duration)));g.fillRect(d.x+Math.sin(n*4)*14+age*(n-2)*7,d.y-age*(18+n*4),size,size)}
  for(const piece of d.pieces){g.fillStyle(piece.color,Math.min(1,piece.life*1.5));g.fillRect(piece.x,piece.y,piece.size,piece.size*.65)}
  if(a.type==='gume'&&t<.45){g.lineStyle(2,0xaaffff,1-t/.45);g.lineBetween(d.x-25-t*60,d.y-26,d.x+22+t*60,d.y+20)}
  if(a.type==='sucata'&&t<.65){g.fillStyle(0x8cffff,Math.max(0,Math.sin(t*40))*(1-t/.65));g.fillRect(d.x-3,d.y-6,5,5)}
 }}
 setupMouse(){const canvas=this.game.canvas;
  const locate=e=>{const rect=canvas.getBoundingClientRect();this.mouseAim.x=(e.clientX-rect.left)/rect.width*W;this.mouseAim.y=(e.clientY-rect.top)/rect.height*H;this.mouseAim.valid=this.mouseAim.x>=0&&this.mouseAim.x<=W&&this.mouseAim.y>109&&this.mouseAim.y<H};
  canvas.addEventListener('pointermove',e=>locate(e));canvas.addEventListener('pointerdown',e=>{locate(e);if(e.button===0&&this.state==='play'&&this.mouseAim.valid){e.preventDefault();this.mouseAim.down=true;this.attack(this.player)}});
  canvas.addEventListener('pointerleave',()=>{this.mouseAim.down=false;this.mouseAim.valid=false});canvas.addEventListener('pointercancel',()=>this.mouseAim.down=false);
  window.addEventListener('pointerup',()=>this.mouseAim.down=false);window.addEventListener('blur',()=>this.mouseAim.down=false);
 }
 aimVector(a){if(!a.controlled)return {x:a.face,y:0};if(!this.mouseAim.valid)return {x:a.face,y:0};const dx=this.mouseAim.x+this.cameras.main.scrollX-a.x,dy=this.mouseAim.y-(a.y-28),len=Math.hypot(dx,dy);return len>1?{x:dx/len,y:dy/len}:{x:a.face,y:0}}
 meleeVector(aim){return Math.abs(aim.y)>Math.abs(aim.x)?{x:0,y:Math.sign(aim.y)}:{x:Math.sign(aim.x)||1,y:0}}

 burst(x,y,color,n){for(let i=0;i<n;i++)this.particles.push({x,y,vx:(Math.random()-.5)*200,vy:(Math.random()-.6)*180,life:.4+Math.random()*.3,color})}
 attack(a){if(this.state!=='play'||a.attack>0||a.dashTime>0||!a.alive)return;const d=R.bodies[a.type],aim=this.aimVector(a);if(Math.abs(aim.x)>.15)a.face=aim.x>0?1:-1;
  a.attack=a.controlled?d.rate:a.type==='vigia'?1.45:1.1;a.action=.28;a.attackAim=a.type==='vigia'?aim:this.meleeVector(aim);void 0;
  const u=a.attackAim;if(a.type==='vigia'){const speed=a.controlled?640:330;this.shots.push({x:a.x+u.x*25,y:a.y-28+u.y*25,vx:u.x*speed,vy:u.y*speed,owner:a,team:a.controlled,life:1.6,damage:a.controlled?this.playerDamage(d.damage):12})}
  else{for(const target of this.actors){if(!target.alive||target.controlled===a.controlled)continue;const dx=target.x-a.x,dy=(target.y-28)-(a.y-28),along=dx*u.x+dy*u.y,across=Math.abs(dx*u.y-dy*u.x);if(along>=-10&&along<=d.range+14&&across<30)this.hit(target,a.controlled?this.playerDamage(d.damage):16,a)}}
 }

 reactorDuration(){return 4-.35*R.upgradeLevel(this,'reactor')}
 startDash(a){const d=R.dashes[a.type];if(this.state!=='play'||!a.alive||!a.controlled||a.dashCooldown>0||a.dashTime>0)return false;
  if(!a.ground&&(!d.air||a.airDashUsed))return false;
  a.dashTime=d.duration;a.dashCooldown=d.cooldown;a.dashDir=a.face;a.dashHits=new Set();a.action=0;if(!a.ground)a.airDashUsed=true;
  a.vx=a.dashDir*d.speed;a.vy=0;this.burst(a.x,a.y-24,d.color,7);SFX.play('dash',a.x);return true;
 }
 tickDash(a,dt){a.dashCooldown=Math.max(0,(a.dashCooldown||0)-dt);if(!(a.dashTime>0))return;
  if(a.type==='vigia')for(const enemy of this.actors){if(!enemy.alive||enemy.controlled||a.dashHits.has(enemy)||Math.abs(enemy.y-a.y)>48)continue;
   if(enemy.x>=Math.min(a.prevX,a.x)-24&&enemy.x<=Math.max(a.prevX,a.x)+24){a.dashHits.add(enemy);this.hit(enemy,this.playerDamage(22),a);if(enemy.alive)enemy.x=Phaser.Math.Clamp(enemy.x+a.dashDir*28,enemy.minX,enemy.maxX)}
  }
  a.dashTime=Math.max(0,a.dashTime-dt);
 }
 playerDamage(base){return base*(1+.05*R.upgradeLevel(this,'power'))}
 offerUpgrade(){
  const choices=R.upgrades.filter(u=>!this.upgrades.includes(u.id));this.rewardPending=choices.length>0;
  ui.title.textContent='Núcleo recuperado';ui.story.textContent='Setor concluído. Escolha uma melhoria para sua consciência. Ela acompanha todas as trocas de corpo.';
  ui.button.disabled=this.rewardPending;ui.button.innerHTML='REJOGAR COM MELHORIAS <span>↗</span>';
  ui.hint.textContent=choices.length?'Nesta prévia, você testa a recompensa ao rejogar o Setor Zero.':'Todas as melhorias estão ativas nesta sessão.';
  document.querySelector('#upgrades').innerHTML=choices.map(u=>`<button type="button" class="upgrade" data-upgrade="${u.id}"><b>${u.label}</b><span>${u.description}</span></button>`).join('');
  document.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>this.chooseUpgrade(b.dataset.upgrade));
 }
 chooseUpgrade(id){if(this.state!=='win'||!this.rewardPending||!R.upgrades.some(u=>u.id===id)||(this.upgrades.length&&this.upgrades[0]!==id)||(this.upgradeTier||0)>=5)return false;
  this.upgrades=[id];this.upgradeTier=(this.upgradeTier||0)+1;this.rewardPending=false;ui.button.disabled=false;const u=R.upgrades.find(u=>u.id===id);
  document.querySelector('#upgrades').innerHTML='';ui.story.textContent=u.label+' · nível '+this.upgradeTier+'/5. '+u.effect(this.upgradeTier);
  ui.hint.textContent='APENAS UM · Esta é sua única evolução durante a campanha.';SFX.play('upgrade');return true;
 }
 dropThrough(a){if(a.dashTime>0||!a.ground||a.dropLock>0)return false;const support=a.support||this.platforms.find(p=>Math.abs(a.y-p.y)<2&&a.x>p.x&&a.x<p.x+p.w);if(!support||support.y===FLOOR)return false;
  a.dropPlatform=support;a.dropLock=.3;a.ground=false;a.support=null;a.y+=3;a.vy=Math.max(a.vy,85);return true;
 }
 move(a,dt){const lastY=a.y;a.prevX=a.x;a.dropLock=Math.max(0,(a.dropLock||0)-dt);a.x=Math.max(24,Math.min(WORLD-24,a.x+a.vx*dt));if(a.dashTime>0){a.vy=0}else{a.vy+=1250*dt}a.y+=a.vy*dt;a.ground=false;a.support=null;
  const land=this.platforms.filter(p=>p!==a.dropPlatform&&a.x+15>p.x&&a.x-15<p.x+p.w&&a.vy>=0&&lastY<=p.y+2&&a.y>=p.y).sort((a,b)=>a.y-b.y)[0];
  if(land){a.y=land.y;a.vy=0;a.ground=true;a.support=land;a.airDashUsed=false}if(a.dropPlatform&&a.y>a.dropPlatform.y+8)a.dropPlatform=null;if(a.y>680)this.hit(a,999,null);
 }
 enemyAI(a,dt){const dx=this.player.x-a.x,dy=this.player.y-a.y;const sees=Math.abs(dx)<510&&Math.abs(dy)<65;
  if(sees){a.face=dx>0?1:-1;if(a.type==='gume')a.vx=Math.abs(dx)>65?a.face*125:0;else a.vx=Math.abs(dx)>340?a.face*65:Math.abs(dx)<160?-a.face*75:0;
   if(Math.abs(dx)<R.bodies[a.type].range)this.attack(a);
  }else{if(a.x<=a.patrolMin+2)a.patrolDir=1;if(a.x>=a.patrolMax-2)a.patrolDir=-1;a.vx=a.patrolDir*(a.type==='gume'?70:42);a.face=a.patrolDir}
  if(a.x+a.vx*dt<a.minX||a.x+a.vx*dt>a.maxX){a.vx=0;a.patrolDir*=-1}
  if(a.type==='gume'&&a.ground&&dy< -60&&dy> -125&&Math.abs(dx)<180){a.vy=-550;a.ground=false}
 }

 interact(){const p=this.player;for(const r of this.relays)if(!r.on&&Math.abs(r.x-p.x)<65&&Math.abs(r.y-p.y)<55){r.on=true;this.drawWorld();this.burst(r.x,r.y-34,0x77e9e9,20);tone(760,.2,'sine');this.say(this.relays.every(r=>r.on)?'Três terminais ativos. Alcance a porta à direita.':'Terminal ativo. Continue pelo setor.',4)}if(p.x>3450){if(this.relays.every(r=>r.on)&&this.transfers>0)this.end(true);else this.say(this.transfers===0?'A porta precisa reconhecer seu núcleo em outro corpo. Deixe um autômato causar o golpe fatal.':'Ative os três terminais para abrir a saída.',5)}}
 updateHUD(){const p=this.player,d=R.bodies[p.type],g=this.hud;g.clear();g.fillStyle(0x07111a,.92);g.fillRect(0,0,W,109);g.lineStyle(1,0x263d49);g.lineBetween(0,109,W,109);g.fillStyle(0x243641);g.fillRect(30,52,185,8);g.fillStyle(p.hp<22?0xe6ad65:0x74dfe0);g.fillRect(30,52,185*Math.max(0,p.hp/p.maxHp),8);g.fillStyle(0x273742);g.fillRect(254,52,156,8);g.fillStyle(this.reactor>0?0xd6a05a:0x6fe8ef);g.fillRect(254,52,156*(1-this.reactor/this.reactorDuration()),8);this.hudTitle.setText(d.label+'   '+Math.ceil(p.hp)+' / '+p.maxHp);this.hudStatus.setText('CORPO ATUAL                    '+(this.reactor>0?'RECARGA '+this.reactor.toFixed(1)+' s':'NÚCLEO PRONTO'+(this.upgrades.length?' · '+this.upgrades.length+' UP':'')));const dash=R.dashes[p.type];this.dashStatus.setText(OUPrefs.keyName(OUPrefs.current.bindings.dash)+' · '+dash.label+'\n\n'+(p.dashCooldown>0?'RECARGA '+p.dashCooldown.toFixed(1)+' s':(!p.ground&&!dash.air?'USE NO CHÃO':p.airDashUsed?'POUSE PARA RECARREGAR':'DASH PRONTO')));const n=this.relays.filter(r=>r.on).length;this.objective.setText('SETOR ZERO / ESCAPE DA INSTALAÇÃO\n\nTERMINAIS '+n+'/3     TRANSFERÊNCIAS '+this.transfers);this.caption.setText(this.messageTime>0?this.message:this.keyLabel('dash')+': dash   ·   '+this.keyLabel('down')+': descer   ·   '+this.keyLabel('attack')+': atacar');}
 renderActors(dt){for(const a of this.actors){if(!a.alive)continue;a.sprite.setPosition(a.x,a.y+2).setFlipX(a.face<0);a.sprite.setRotation(a.dashTime>0?a.face*.08:0);let frame=0;if(a.dashTime>0)frame=a.type==='gume'?9:5;else if(a.action>0)frame=12+Math.min(3,Math.floor((.28-a.action)/.07));else if(!a.ground)frame=a.vy< -100?9:a.vy<100?10:11;else if(Math.abs(a.vx)>5)frame=4+Math.floor(this.clock*10)%4;else frame=Math.floor(this.clock*4)%4;a.sprite.setFrame(frame);if(a.controlled)a.sprite.clearTint();else a.sprite.setTint(0xb8b9ad);a.sprite.setAlpha(a.invuln>0&&Math.floor(this.clock*18)%2?.5:1)}}
 drawEffects(dt){const g=this.effects;g.clear();this.drawDeathEffects(g);if(this.state==='play'&&this.mouseAim.valid){const x=this.mouseAim.x+this.cameras.main.scrollX,y=this.mouseAim.y;g.lineStyle(1,0xa0faff,.9);g.lineBetween(x-6,y,x+6,y);g.lineBetween(x,y-6,x,y+6)}for(const a of this.actors){if(!a.alive)continue;if(a.dashTime>0){const d=R.dashes[a.type];for(let i=1;i<=3;i++){g.lineStyle(5-i,d.color,.55/i);g.lineBetween(a.x-a.dashDir*(i*15),a.y-27,a.x-a.dashDir*(i*15+25),a.y-27)}}if(a.controlled){g.lineStyle(2,this.reactor>0?0xd8a55b:0x76f3f5,.9);g.strokeEllipse(a.x,a.y+1,45,8);g.fillStyle(0x80fcff);g.fillTriangle(a.x-5,a.y-80,a.x+5,a.y-80,a.x,a.y-73)}else if(a.hp<a.maxHp||Math.abs(a.x-this.player.x)<450){g.fillStyle(0x09131c);g.fillRect(a.x-22,a.y-73,44,4);g.fillStyle(0xbe8853);g.fillRect(a.x-22,a.y-73,44*a.hp/a.maxHp,4)}if(a.action>.04&&R.bodies[a.type].melee){const u=a.attackAim||{x:a.face,y:0},reach=R.bodies[a.type].range,angle=Math.atan2(u.y,u.x),swing=(.28-a.action)/.28;g.lineStyle(a.type==='gume'?4:7,a.type==='gume'?0x78f7ff:0xffb445,.9);if(a.type==='gume'){let prior=null;for(let i=0;i<=6;i++){const t=angle-.65+i*.22,pt={x:a.x+Math.cos(t)*reach,y:a.y-28+Math.sin(t)*reach};if(prior)g.lineBetween(prior.x,prior.y,pt.x,pt.y);prior=pt}g.lineBetween(a.x,a.y-28,a.x+Math.cos(angle-.6+swing*1.2)*reach,a.y-28+Math.sin(angle-.6+swing*1.2)*reach)}else g.lineBetween(a.x+u.x*14,a.y-28+u.y*14,a.x+u.x*reach,a.y-28+u.y*reach)}}for(const s of this.shots){g.fillStyle(s.team?0x80faff:0xffb960);g.lineStyle(4,s.team?0x80faff:0xffb960);const len=Math.hypot(s.vx,s.vy||0)||1;g.lineBetween(s.x-s.vx/len*10,s.y-(s.vy||0)/len*10,s.x+s.vx/len*5,s.y+(s.vy||0)/len*5)}for(const p of this.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;g.fillStyle(p.color,Math.max(0,p.life*2));g.fillRect(p.x,p.y,3,3)}this.particles=this.particles.filter(p=>p.life>0);if(this.transition>0&&this.transferLine){g.lineStyle(4,0x99ffff,this.transition/.65);g.lineBetween(this.transferLine.from.x,this.transferLine.from.y-32,this.transferLine.to.x,this.transferLine.to.y-32)}}
 update(time,delta){Settings.syncMenu();if(this.state==='settings')return;const dt=Math.min(delta/1000,.035);this.clock+=dt;if(this.state==='dying'){this.animateDeaths(dt);this.drawEffects(dt);this.deathWait-=dt;if(this.deathWait<=0)this.end(false,this.deathReason);return}const pressed=k=>Phaser.Input.Keyboard.JustDown(this.bindings[k]);const esc=pressed('pause'),restart=pressed('restart'),enter=Phaser.Input.Keyboard.JustDown(this.keys.ENTER);if(enter&&this.state!=='play'&&!['BUTTON','INPUT','SELECT'].includes(document.activeElement?.tagName))this.primary();if(restart&&['play','paused','dead'].includes(this.state)){this.reset();this.state='play';ui.overlay.style.display='none';this.showHUD(true)}if(esc&&['play','paused'].includes(this.state)){if(this.state==='paused')this.primary();else{this.state='paused';ui.overlay.style.display='flex';ui.eyebrow.textContent='SINAL EM ESPERA';ui.title.style.fontSize='65px';ui.title.textContent='Pausa';ui.story.textContent='O núcleo aguarda seu retorno.';ui.brief.style.display='none';ui.button.innerHTML='CONTINUAR <span>↗</span>';ui.hint.textContent=this.keyLabel('pause')+' para voltar · '+this.keyLabel('restart')+' para reiniciar'}}
  if(this.state!=='play'){this.mouseAim.down=false;this.renderActors(dt);return}this.elapsed+=dt;this.messageTime-=dt;this.reactor=Math.max(0,this.reactor-dt);this.transition=Math.max(0,this.transition-dt);const step=this.transition>0?dt*.22:dt,p=this.player;const down=k=>this.bindings[k].isDown;let axis=(down('right')||touch.right?1:0)-(down('left')||touch.left?1:0);p.vx=axis*R.bodies[p.type].speed;if(axis&&p.dashTime<=0)p.face=axis;if(this.mouseAim.valid&&p.dashTime<=0){const aim=this.aimVector(p);if(Math.abs(aim.x)>.15)p.face=aim.x>0?1:-1}const dashPressed=pressed('dash')||(touch.dash&&!this.touchPrev.dash);if(dashPressed)this.startDash(p);if(p.dashTime>0){p.vx=p.dashDir*R.dashes[p.type].speed;p.face=p.dashDir}const jump=pressed('jump')||(touch.jump&&!this.touchPrev.jump);const dropping=down('down')||touch.down;if(dropping)this.dropThrough(p);if(jump&&p.ground&&!dropping&&p.dashTime<=0){p.vy=-R.bodies[p.type].jump;p.ground=false;SFX.play('jump',p.x,.6)}if(this.mouseAim.down||down('attack')||touch.attack)this.attack(p);if(pressed('interact')||(touch.interact&&!this.touchPrev.interact))this.interact();this.touchPrev={...touch};if(this.state!=='play')return;
  for(const a of this.actors){if(!a.alive)continue;a.attack=Math.max(0,a.attack-step);a.action=Math.max(0,a.action-step);a.invuln=Math.max(0,a.invuln-step);if(!a.controlled)this.enemyAI(a,step);this.move(a,step);this.tickDash(a,step);if(a.controlled&&this.hazards.some(h=>a.x>h.x&&a.x<h.x+h.w&&a.y>=FLOOR-3))this.hit(a,16,null);if(this.state!=='play')break}
  for(const s of this.shots){if(this.state!=='play')break;const x0=s.x,y0=s.y;s.x+=s.vx*step;s.y+=(s.vy||0)*step;s.life-=step;const hits=this.actors.filter(a=>a.alive&&a.controlled!==s.team).map(a=>({a,t:R.segmentHit(x0,y0,s.x,s.y,a.x-(a.hitWidth||18),a.y-(a.hitHeight||56),a.x+(a.hitWidth||18),a.y)})).filter(h=>h.t!==null).sort((a,b)=>a.t-b.t);if(hits.length){this.hit(hits[0].a,s.damage,s.owner);s.life=0}}this.shots=this.shots.filter(s=>s.life>0);if((this.levelIndex||0)===0&&this.transfers===0&&!this.actors.some(a=>a.alive&&!a.controlled)){this.spawn('vigia',Math.min(3350,this.player.x+180),500);this.reinforced=true;this.say('Reforço detectado. A saída exige uma transferência de consciência.',6)}
  const target=Phaser.Math.Clamp(this.player.x-380,0,WORLD-W);this.cameras.main.scrollX=Phaser.Math.Linear(this.cameras.main.scrollX,target,Math.min(1,dt*5));this.prompt.setVisible(false);for(const r of this.relays)if(!r.on&&Math.abs(this.player.x-r.x)<100&&Math.abs(this.player.y-r.y)<65)this.prompt.setPosition(r.x,r.y-77).setText(this.keyLabel('interact')+' · ATIVAR').setVisible(true);if(this.player.x>3400)this.prompt.setPosition(3530,280).setText(this.keyLabel('interact')+' · SAIR').setVisible(true);if(this.elapsed>7&&this.elapsed<7+dt)this.say(this.keyLabel('attack')+' dispara ou golpeia. Para trocar de corpo, receba um golpe fatal de um autômato.',6);this.animateDeaths(dt);this.renderActors(dt);this.drawEffects(step);this.updateHUD();
 }
}
OUC.install(Sector);
Expedition.install(Sector);
Singular.install(Sector);Resonance.install(Sector);SFX.install(Sector);
const game=new Phaser.Game({type:Phaser.AUTO,parent:'game',width:W,height:H,backgroundColor:'#0c1722',pixelArt:true,roundPixels:true,scene:Sector,scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},audio:{noAudio:true}});
window.addEventListener('blur',()=>{for(const key of Object.keys(touch))touch[key]=false;if(window.__OU?.state==='play'){window.__OU.keys.ESC.isDown=false;window.__OU.state='paused';ui.overlay.style.display='flex';ui.title.textContent='Pausa';ui.story.textContent='Clique em continuar para voltar ao setor.';ui.eyebrow.textContent='SINAL EM ESPERA';ui.brief.style.display='none';ui.button.innerHTML='CONTINUAR <span>↗</span>'}});
