const Settings={scene:null,waiting:null,previous:null,lastState:null,
 attach(scene){this.scene=scene;scene.applyControls();scene.applyResolution();this.refresh();this.syncMenu()},
 refresh(){const p=OUPrefs.current;document.querySelector('#volume').value=p.volume;document.querySelector('#volume-value').textContent=p.volume+'%';document.querySelector('#resolution').value=p.resolution;document.querySelector('#bindings').innerHTML=Object.entries(OUPrefs.actions).map(([a,label])=>`<div class="binding"><span>${label}</span><button type="button" data-bind="${a}" aria-label="Alterar tecla: ${label}">${OUPrefs.keyName(p.bindings[a])}</button></div>`).join('');document.querySelectorAll('[data-bind]').forEach(b=>b.onclick=()=>{this.waiting=b.dataset.bind;document.querySelector('#binding-message').textContent='Pressione a nova tecla para '+OUPrefs.actions[this.waiting].toLowerCase()+'. Esc cancela.';b.textContent='…'});this.updateHints()},
 updateHints(){const b=OUPrefs.current.bindings,k=a=>OUPrefs.keyName(b[a]);document.querySelector('.bar').innerHTML=`<p><kbd>${k('left')}</kbd><kbd>${k('right')}</kbd> mover <kbd>${k('jump')}</kbd> saltar <kbd>${k('down')}</kbd> descer <kbd>${k('dash')}</kbd> dash <kbd>Mouse 1</kbd> atacar / <kbd>${k('attack')}</kbd> alternativa <kbd>${k('interact')}</kbd> interagir</p><p><kbd>${k('pause')}</kbd> pausa <kbd>${k('restart')}</kbd> reiniciar</p>`},
 save(){const ok=OUPrefs.save();document.querySelector('#settings-save').textContent=ok?'Preferências salvas neste navegador.':'Preferências ativas nesta sessão; o navegador bloqueou o salvamento.'},
 open(){if(!this.scene||document.querySelector('#settings-dialog').open)return;SFX.stop();this.previous=this.scene.state;this.scene.state='settings';this.scene.mouseAim.down=false;this.scene.input.keyboard.enabled=false;this.scene.input.keyboard.clearCaptures();this.scene.input.keyboard.resetKeys();for(const k of Object.keys(touch))touch[k]=false;this.waiting=null;this.refresh();document.querySelector('#binding-message').textContent='Clique em uma tecla para alterá-la.';document.querySelector('#settings-dialog').showModal();document.querySelector('#close-settings').focus()},
 close(){const dialog=document.querySelector('#settings-dialog');if(!dialog.open)return;this.waiting=null;dialog.close();this.scene.state=this.previous;this.scene.input.keyboard.enabled=true;this.scene.applyControls();this.save();this.syncMenu()},
 syncMenu(){const state=this.scene?.state;if(state===this.lastState)return;this.lastState=state;document.querySelector('#restart-menu').hidden=state!=='paused';document.querySelector('#home-menu').hidden=!['paused','dead','win'].includes(state);document.querySelector('#open-pause').disabled=state!=='play';},
};
document.querySelectorAll('[data-settings]').forEach(b=>b.onclick=()=>Settings.open());
document.querySelector('#close-settings').onclick=()=>Settings.close();
document.querySelector('#settings-dialog').oncancel=e=>{e.preventDefault();if(Settings.waiting){Settings.waiting=null;Settings.refresh();document.querySelector('#binding-message').textContent='Alteração cancelada.'}else Settings.close()};
document.querySelector('#volume').oninput=e=>{OUPrefs.current.volume=Number(e.target.value);SFX.stop();document.querySelector('#volume-value').textContent=e.target.value+'%';Settings.save()};
document.querySelector('#test-sound').onclick=()=>SFX.play('shot',null,1,true);
document.querySelector('#resolution').onchange=e=>{OUPrefs.current.resolution=e.target.value;Settings.scene.applyResolution();Settings.save()};
document.querySelector('#restore-settings').onclick=()=>{OUPrefs.current=OUPrefs.normalize(null);Settings.waiting=null;Settings.scene.applyResolution();Settings.refresh();Settings.save();document.querySelector('#binding-message').textContent='Configurações padrão restauradas.'};
document.querySelector('#open-pause').onclick=()=>Settings.scene?.pauseMenu();
document.querySelector('#restart-menu').onclick=()=>Settings.scene?.restartRun();
document.querySelector('#home-menu').onclick=()=>Settings.scene?.mainMenu();
window.addEventListener('keydown',e=>{if(!document.querySelector('#settings-dialog').open)return;if(!Settings.waiting)return;e.preventDefault();e.stopImmediatePropagation();if(e.repeat)return;if(e.key==='Escape'){Settings.waiting=null;Settings.refresh();document.querySelector('#binding-message').textContent='Alteração cancelada.';return}const result=OUPrefs.rebind(OUPrefs.current,Settings.waiting,e.keyCode);if(result.ok){Settings.waiting=null;Settings.save();Settings.refresh();document.querySelector('#binding-message').textContent='Tecla alterada.'}else document.querySelector('#binding-message').textContent=result.message;},true);
