/* Original synthesized effects: cached mono buffers, spatial falloff, bounded voices. */
const SFX={cache:new Map(),voices:new Set(),last:new Map(),
 specs:{shot:[.16,760,85,.35],laser:[.28,1700,140,.12],grenade:[.22,190,55,.6],turret:[.18,430,70,.5],sword:[.16,580,180,.85],punch:[.12,150,45,.7],hammer:[.3,110,30,.8],hurt:[.18,240,65,.7],metal:[.25,470,95,.6],collapse:[.7,180,35,.8],explosion:[.75,100,24,1],jump:[.14,170,550,.08],land:[.12,100,32,.65],step:[.065,170,70,.7],dash:[.23,750,110,.7],transfer:[.9,180,1450,.12],ready:[.22,550,1100,.02],pickup:[.3,620,1300,.03],terminal:[.36,400,900,.06],upgrade:[.7,330,990,.03],door:[.6,100,38,.6],ui:[.055,650,450,.03],win:[.9,330,1320,.04],lose:[.8,260,45,.18],emp:[.65,1100,55,.65],pulse:[.5,240,45,.25],charge:[.7,120,800,.2],slam:[.65,85,22,.9],steam:[.7,800,320,1],alarm:[.4,650,360,.12]},
 unlock(){try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}catch{return null}},
 buffer(name,ctx){if(this.cache.has(name))return this.cache.get(name);const [dur,start,end,noise]=this.specs[name]||this.specs.ui,rate=ctx.sampleRate,b=ctx.createBuffer(1,Math.ceil(dur*rate),rate),out=b.getChannelData(0);let phase=0,low=0,seed=12345;for(let i=0;i<out.length;i++){const t=i/rate,q=t/dur;seed=(Math.imul(seed,1664525)+1013904223)|0;const n=seed/2147483648;low+=.13*(n-low);const freq=start*Math.pow(end/start,q);phase+=Math.PI*2*freq/rate;const body=Math.sin(phase)+.22*Math.sin(phase*2.01)+.10*Math.sin(phase*3.98);let env=Math.min(1,t/.006)*Math.pow(1-q,2);if(['transfer','upgrade','win','charge'].includes(name))env=Math.min(1,t/.04)*Math.sin(Math.PI*q);const rhythm=name==='emp'?.65+.35*Math.sin(t*90):1;out[i]=Math.tanh((body*(1-noise)+low*noise*3)*1.2)*env*rhythm*.65}this.cache.set(name,b);return b},
 play(name,x=null,gain=1,preview=false){if(document.hidden||!OUPrefs.current.volume)return;const scene=window.__OU;if(!preview&&scene&&['paused','settings'].includes(scene.state)&&!['ui','ready'].includes(name))return;const ctx=this.unlock();if(!ctx)return;const now=ctx.currentTime,key=name+(x===null?'':':world');if(now-(this.last.get(key)??-1)<(name==='step'?.09:.035)||this.voices.size>=20)return;let pan=0;if(x!==null&&scene?.player){const distance=Math.abs(x-scene.player.x);if(distance>950)return;gain*=Math.max(0,1-distance/1000);pan=Math.max(-.8,Math.min(.8,(x-scene.player.x)/600))}this.last.set(key,now);if(!this.output&&ctx.createDynamicsCompressor){this.output=ctx.createDynamicsCompressor();this.output.threshold.value=-16;this.output.ratio.value=5;this.output.connect(ctx.destination)}const destination=this.output||ctx.destination;const source=ctx.createBufferSource(),level=ctx.createGain(),stereo=ctx.createStereoPanner?.();source.buffer=this.buffer(name,ctx);level.gain.value=.28*gain*OUPrefs.current.volume/100;source.connect(level);if(stereo){stereo.pan.value=pan;level.connect(stereo);stereo.connect(destination)}else level.connect(destination);const voice={source,level,stereo};this.voices.add(voice);source.onended=()=>{source.disconnect();level.disconnect();stereo?.disconnect();this.voices.delete(voice)};source.start();},
 stop(){for(const v of this.voices){try{v.source.stop()}catch{}v.source.disconnect();v.level.disconnect();v.stereo?.disconnect()}this.voices.clear()},
 install(Sector){const p=Sector.prototype,old={};for(const k of ['attack','move','hit','primary','end','reset','update','resolveECOAttack','emitPulse','enemyAI'])old[k]=p[k];
 p.attack=function(a){const before=a.attack;old.attack.call(this,a);if(before<=0&&a.attack>0)SFX.play({sucata:'punch',vigia:'shot',gume:'sword',forja:'grenade',prisma:'laser',ancora:'hammer',turret:'turret'}[a.type]||'shot',a.x,a.controlled?1:.6)};
 p.move=function(a,dt){const grounded=a.ground,fall=a.vy;old.move.call(this,a,dt);if(a.controlled&&a.alive){if(!grounded&&a.ground&&fall>100)SFX.play('land',a.x,.6);a.stepSound=(a.stepSound||0)-dt;if(a.ground&&Math.abs(a.vx)>50&&a.dashTime<=0&&a.stepSound<=0){SFX.play('step',a.x,.24);a.stepSound=.29}}};
 p.hit=function(a,damage,killer){const hp=a.hp,controlled=a.controlled,player=this.player;old.hit.call(this,a,damage,killer);if(a.hp<hp&&a.alive)SFX.play(controlled?'hurt':'metal',a.x,controlled?.85:.45);if(player!==this.player)SFX.play('transfer',this.player.x)};
 p.primary=function(){SFX.unlock();SFX.play('ui');old.primary.call(this)};
 p.end=function(win,reason){const prior=this.state;old.end.call(this,win,reason);if(prior!==this.state)SFX.play(win?'win':'lose')};
 p.reset=function(){SFX.stop();old.reset.call(this)};
 p.resolveECOAttack=function(){const f=this.finalEncounter;SFX.play({fan:'shot',slam:'slam',sweep:'laser',pulse:'pulse',emp:'emp'}[f.kind],this.boss.x);old.resolveECOAttack.call(this)};
 p.emitPulse=function(a,emp){if(a.type!=='eco')SFX.play(emp?'emp':'pulse',a.x);old.emitPulse.call(this,a,emp)};
 p.enemyAI=function(a,dt){const charge=a.empCharge;old.enemyAI.call(this,a,dt);if(!(charge>0)&&a.empCharge>0)SFX.play('charge',a.x,.5)};
 p.update=function(time,delta){const state=this.state,reactor=this.reactor,emp=this.empLock,charge=this.finalEncounter?.attackTime,vents=(this.vents||[]).map(v=>v.active);old.update.call(this,time,delta);if(this.state!==state&&['paused','settings','menu'].includes(this.state))SFX.stop();if(this.state==='play'){if((reactor>0&&this.reactor===0)||(emp>0&&this.empLock===0))SFX.play('ready',null,.55);if(!(charge>0)&&this.finalEncounter?.attackTime>0)SFX.play('charge',this.boss.x,.6);(this.vents||[]).forEach((v,i)=>{if(v.active&&!vents[i])SFX.play('steam',v.x,.3)})}};
 document.addEventListener?.('pointerdown',e=>{SFX.unlock();if(e.target.closest?.('button'))SFX.play('ui',null,.4)});
 window.addEventListener('blur',()=>SFX.stop());
 document.addEventListener?.('visibilitychange',()=>{if(document.hidden)SFX.stop()});
 }
};
